In [ ]:
###############################################################################
# CAMIA: Context‑Aware Membership Inference Attack – Annotated Implementation  #
# ──────────────────────────────────────────────────────────────────────────── #
# QUICK ROADMAP                                                                #
#   • Cell‑1  –  Imports, device set‑up.                                       #
#   • Cell‑2  –  Helper for picking HF model names (Pythia / GPT‑Neo).         #
#   • Cell‑3  –  Core signal extraction:  per‑token loss, calibration,         #
#                sequence‑level statistics (cut‑off, slope, ApEn, LZ, etc.)    #
#   • Cell‑4  –  Edgington p‑value combiner and logistic‑regression w/         #
#                Group‑PCA (Section 4 of the paper).                           #
#   • Cell‑5  –  Utility for computing ROC metrics and visual inspection.      #
#   • Cell‑6  –  Minimal end‑to‑end demo on the public MIMIR benchmark.        #
#   • Cell‑7  –  Diagnostic figures reproducing key plots from Figures 2–8.    #
#   • Cell‑8  –  Aggregation helper for multiple experimental runs.            #
#                                                                              #
###############################################################################

In [2]:
###############################################################################
# Cell 1 – imports & global config                                            #
###############################################################################
import math, json, os, random, glob, bisect
from collections import defaultdict
import itertools
from itertools import islice

import numpy as np
import torch, torch.nn as nn
from tqdm import tqdm
import matplotlib.pyplot as plt
from transformers import AutoModelForCausalLM, AutoTokenizer, AutoModelForSeq2SeqLM
from datasets   import load_dataset
from sklearn.decomposition import PCA
from sklearn.linear_model  import LogisticRegression
from sklearn.metrics       import roc_auc_score, roc_curve

# --------------------------------------------------------------------------- #
device = "cuda" if torch.cuda.is_available() else "cpu"
print("✔ using", device)

# ---------- master knobs you may tweak in ONE place ------------------------ #
class C:                       # ← just a namespace
    MAX_LEN_CE   = 1024         # truncate only for CE loss
    CE_SUB_BS    = 32          # chunk size of CE pass
    fp16_ce        = True
    NEI_K        = 0          # neighbours per passage
    NEI_FILL_BS  = 16          # T5 batch on CPU
    NEI_FILL_MDL = "t5-large"  # keep small to save RAM
    NEI_WEIGHT   = 0          # weight in Edgington combiner
    STORE_NEI    = True
    STORE_SEQ    = True
    CUT_TPRIMES    = {"T":None,"200":200,"300":300}
    CB_TAU_LIST    = [1,2,3]
    LZ_BIN_LIST    = [3,4,5]
    SLOPE_TPRIMES  = [600,800,1000]
    APEN_TPRIMES   = [600,800,1000]
    STORE_FULL_SEQ = True

✔ using cuda

In [3]:
###############################################################################
# Cell 2 – Utility: map (suite,size) → HuggingFace model name                  #
#                                                                              #
# Matches Appendix B in the paper.  The deduped variants are handled by a      #
# boolean flag and are needed to replicate the Pythia‑deduped experiments.     #
###############################################################################

def get_model_name(suite: str, size: str, deduped: bool = False) -> str:
    """Return canonical HF repo string for the requested model."""
    suite = suite.lower()
    size = size.lower()
    if suite == "pythia":
        base = f"EleutherAI/pythia-{size}"
        return base + ("-deduped" if deduped else "")
    if suite == "gpt-neo":
        mapping = {"125m": "125M", "1.3b": "1.3B", "2.7b": "2.7B"}
        if size not in mapping:
            raise ValueError(f"Unsupported GPT‑Neo size: {size}")
        return f"EleutherAI/gpt-neo-{mapping[size]}"
    raise ValueError(f"Unknown suite: {suite}")

In [ ]:
###############################################################################
# DO NOT RUN Cell 2.5 – Neighbour generation à la Neighbourhood-Attack (BERT version)   #
###############################################################################
"""
Re-implements the neighbour generator from the original code base:

  • single-token replacement with dropout-masked embedding (p = 0.7)
  • top-k (=100) substitutes per passage
  • encoder-only MLM  ➜  10-40× faster than the former T5 generate() loop
  • two JSON caches:
        cache/neigh_<domain>_<split>_member.json
        cache/neigh_<domain>_<split>_nonmember.json
"""
import os, json, random, math, torch, numpy as np
from tqdm.auto import trange
from datasets import load_dataset
from transformers import (
    BertForMaskedLM,    BertTokenizer,
    DistilBertForMaskedLM, DistilBertTokenizer,
    RobertaForMaskedLM,   RobertaTokenizer,
)

# ───────────────────────────── user knobs ────────────────────────────────────
domain_name = "pubmed_central"             # ← set by sweep script
split_name  = "ngram_7_0.2"
num_samples = 1000
hf_token    = "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"

SEARCH_MODEL = "bert"             #  "bert" | "distilbert" | "roberta"
# pick GPU-1 if it exists, else fall back to GPU-0, else CPU
_n = torch.cuda.device_count()
GPU_SEARCH = f"cuda:{1 if _n > 1 else 0}" if _n else "cpu"

GPU_ATTACK   = "cuda:0"           #  where the *CAMIA* causal-LM will live

NEI_K        = 100                # neighbours per passage
DROPOUT_P    = 0.7
RNG_SEED     = 0
cache_dir    = "cache";  os.makedirs(cache_dir, exist_ok=True)

# ─────────────────────── load passages (unchanged) ───────────────────────────
ds = load_dataset("iamgroot42/mimir", domain_name,
                  split=split_name, token=hf_token)
members    = ds["member"]   [:num_samples]
nonmembers = ds["nonmember"][:num_samples]

# ─────────────────────── MLM & tokenizer choice ──────────────────────────────
if SEARCH_MODEL == "bert":
    tok = BertTokenizer.from_pretrained("bert-base-uncased")
    mlm = BertForMaskedLM.from_pretrained("bert-base-uncased")
elif SEARCH_MODEL == "distilbert":
    tok = DistilBertTokenizer.from_pretrained("distilbert-base-uncased")
    mlm = DistilBertForMaskedLM.from_pretrained("distilbert-base-uncased")
elif SEARCH_MODEL == "roberta":
    tok = RobertaTokenizer.from_pretrained("roberta-base")
    mlm = RobertaForMaskedLM.from_pretrained("roberta-base")
else:
    raise ValueError("SEARCH_MODEL must be bert | distilbert | roberta")

tok.model_max_length = 512
MASK_ID   = tok.mask_token_id
mlm       = mlm.to(GPU_SEARCH).eval()
drop_layer = torch.nn.Dropout(DROPOUT_P)

# ───────────────────────── helper: neighbours for one passage ────────────────
@torch.no_grad()
def neighbours_for_text(text: str, k: int = NEI_K):
    """
    Return `k` neighbours produced by the MLM with embedding-dropout,
    ranked by the pswap score (eq. 4 in the paper).
    """
    enc = tok(text, return_tensors="pt").to(GPU_SEARCH)
    ids = enc.input_ids[0]               # (L,)
    L   = ids.size(0)

    cand2score = {}
    for idx in range(1, L-1):            # authors skip first token
        orig_t = ids[idx]
        # Embed-dropout only at position `idx`
        if SEARCH_MODEL == "roberta":
            embs = mlm.roberta.embeddings(ids.unsqueeze(0))
        elif SEARCH_MODEL == "distilbert":
            embs = mlm.distilbert.embeddings(ids.unsqueeze(0))
        else:  # bert
            embs = mlm.bert.embeddings(ids.unsqueeze(0))
        embs[0, idx] = drop_layer(embs[0, idx])

        logits = mlm(inputs_embeds=embs).logits[0, idx]   # (V,)
        probs  = torch.softmax(logits, dim=-1)

        p_orig = probs[orig_t].item()
        top_p, top_t = torch.topk(probs, k+1)             # may include orig
        for p, t in zip(top_p, top_t):
            tid = t.item()
            if tid == orig_t:       # skip the original word
                continue
            pswap = p.item() / (1 - p_orig + 1e-12)
            cand2score[(idx, tid)] = pswap

    # top-k over *all* positions
    best = sorted(cand2score.items(),
                  key=lambda kv: kv[1], reverse=True)[:k]

    neighbours = []
    ids_np = ids.cpu().numpy()
    for (pos, tid), _ in best:
        new_ids = ids_np.copy()
        new_ids[pos] = tid
        neighbours.append(tok.decode(new_ids, skip_special_tokens=True))

    # sanity: if duplicates slip through (rare) pad with fewer than k
    neighbours = list(dict.fromkeys(neighbours))[:k]
    if len(neighbours) < k:            # very unlikely, but keep shape stable
        neighbours += [text] * (k - len(neighbours))
    return neighbours

# ───────────────────────── table builder & JSON cache ────────────────────────
torch.manual_seed(RNG_SEED)
np.random.seed(RNG_SEED)
random.seed(RNG_SEED)

def build_cache(passages, tag):
    table = []
    for txt in trange(len(passages), desc=f"{tag} neighbours"):
        table.append(neighbours_for_text(passages[txt]))
    path = f"{cache_dir}/neigh_{domain_name}_{split_name}_{tag}.json"
    with open(path, "w") as f:
        json.dump(table, f)
    print("✓ cached →", path)

build_cache(members,    "member")
build_cache(nonmembers, "nonmember")

del mlm; torch.cuda.empty_cache()
print("Neighbour generation completed – search-GPU freed.")

In [ ]:
###############################################################################
# DO NOT RUN Cell 2.5-ALT – Neighbour generation with “highest-loss­-token” heuristic   #
###############################################################################
"""
 • For every passage we compute per-token CE losses with the CAMIA causal-LM.
 • We pick the NEI_K highest-loss positions.
 • For each position we create **one** neighbour via the pswap embedding-dropout
   trick (same as the original implementation).
 • Caches are written to   cache2/neigh2_<domain>_<split>_<tag>.json
   so they never overwrite the original cache/neigh_* files.
"""
import os, json, random, torch, numpy as np, math
from tqdm.auto import tqdm, trange
from datasets import load_dataset
from transformers import (
    BertForMaskedLM,    BertTokenizer,
    DistilBertForMaskedLM, DistilBertTokenizer,
    RobertaForMaskedLM,   RobertaTokenizer,
    AutoModelForCausalLM, AutoTokenizer
)

# ───────────────────────────── user knobs ────────────────────────────────────
domain_name = "pubmed_central"
split_name  = "ngram_7_0.2"
num_samples = 1_000
hf_token    = "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"

suite, size, dedup = "Pythia", "70M", True        # CAMIA-LM
model_name  = get_model_name(suite, size, dedup)

SEARCH_MODEL = "bert"        # "bert" | "distilbert" | "roberta"
NEI_K        = 100           # ONE neighbour per selected token
RNG_SEED     = 0
cache_dir    = "cache2"; os.makedirs(cache_dir, exist_ok=True)

# ───────────────────── CAMIA causal-LM (GPU-0) ──────────────────────────────
tok_lm = AutoTokenizer.from_pretrained(model_name)
tok_lm.add_special_tokens({'pad_token':'[PAD]'})
lm = (AutoModelForCausalLM
      .from_pretrained(model_name,
                       torch_dtype=torch.float16,
                       low_cpu_mem_usage=True)
      .to("cuda:0")
      .eval())

# ───────────────────── MLM for substitutions (GPU-1 or CPU) ────────────────
if SEARCH_MODEL == "bert":
    tok_mlm = BertTokenizer.from_pretrained("bert-base-uncased")
    mlm     = BertForMaskedLM.from_pretrained("bert-base-uncased")
elif SEARCH_MODEL == "distilbert":
    tok_mlm = DistilBertTokenizer.from_pretrained("distilbert-base-uncased")
    mlm     = DistilBertForMaskedLM.from_pretrained("distilbert-base-uncased")
else:  # roberta
    tok_mlm = RobertaTokenizer.from_pretrained("roberta-base")
    mlm     = RobertaForMaskedLM.from_pretrained("roberta-base")

tok_mlm.model_max_length = 512
MLM_DEVICE = "cuda:1" if torch.cuda.device_count() > 1 else "cpu"
mlm = mlm.to(MLM_DEVICE).eval()
MASK_ID   = tok_mlm.mask_token_id
drop_layer = torch.nn.Dropout(0.7)

# ───────────────────── seeding ──────────────────────────────────────────────
torch.manual_seed(RNG_SEED)
np.random.seed(RNG_SEED)
random.seed(RNG_SEED)

# ───────────────────── helpers ──────────────────────────────────────────────
@torch.no_grad()
def token_losses(text: str):
    """List[float] – next-token CE losses from the CAMIA model."""
    enc = tok_lm(text, return_tensors="pt",
                 truncation=True, max_length=C.MAX_LEN_CE).to(lm.device)
    out = lm(enc.input_ids, labels=enc.input_ids)

    # recompute per-token CE so we know which positions hurt most
    logits = out.logits[:, :-1]                     # (1, L-1, V)
    tgt    = enc.input_ids[:, 1:]
    ce = torch.nn.functional.cross_entropy(
            logits.reshape(-1, logits.size(-1)),
            tgt.reshape(-1),
            reduction="none").view(tgt.size())      # (1, L-1)
    mask = tgt.ne(tok_lm.pad_token_id)
    return ce[mask].cpu().tolist()                  # length = # real tokens


@torch.no_grad()
def best_substitute(ids: torch.Tensor, idx: int):
    """
    Single-token replacement at position `idx` (pswap heuristic).
    """
    if SEARCH_MODEL == "roberta":
        embs = mlm.roberta.embeddings(ids.unsqueeze(0))
    elif SEARCH_MODEL == "distilbert":
        embs = mlm.distilbert.embeddings(ids.unsqueeze(0))
    else:
        embs = mlm.bert.embeddings(ids.unsqueeze(0))

    embs[0, idx] = drop_layer(embs[0, idx])

    logits = mlm(inputs_embeds=embs).logits[0, idx]        # (V,)
    probs  = torch.softmax(logits, dim=-1)

    orig_t = ids[idx]
    p_orig = probs[orig_t].item()

    top_p, top_t = torch.topk(probs, NEI_K + 5)            # +5 for safety
    best_tid, best_score = None, -math.inf
    for p, t in zip(top_p, top_t):
        tid = t.item()
        if tid == orig_t:
            continue
        pswap = p.item() / (1 - p_orig + 1e-12)
        if pswap > best_score:
            best_score, best_tid = pswap, tid

    new_ids = ids.clone()
    new_ids[idx] = best_tid
    return tok_mlm.decode(new_ids, skip_special_tokens=True)


def neighbours_for_text(text: str, k: int = NEI_K):
    """
    Generate *k* neighbours by perturbing the k highest-loss tokens
    (CAMIA-loss ranking -> MLM substitute).
    """
    losses = token_losses(text)
    if not losses:
        return [text] * k                   # empty / somehow failed

    # index → high-to-low by CAMIA loss
    top_idx = np.argsort(losses)[::-1]      # descending

    enc_mlm = tok_mlm(text, return_tensors="pt").to(MLM_DEVICE)
    ids_mlm = enc_mlm.input_ids[0]          # (L_mlm,)
    L_mlm   = ids_mlm.size(0)

    neigh, used = [], set()
    for pos in top_idx:
        if pos >= L_mlm or pos in used:     # unmatched or duplicate
            continue
        used.add(pos)
        neigh.append(best_substitute(ids_mlm, pos))
        if len(neigh) == k:
            break

    # pad if we exhausted distinct positions
    neigh.extend([text] * (k - len(neigh)))
    return neigh


def build_cache(passages, tag):
    table = []
    for txt in tqdm(passages, desc=f"{tag} neighbours (loss-top-k)"):
        table.append(neighbours_for_text(txt))
    path = f"{cache_dir}/neigh2_{domain_name}_{split_name}_{tag}.json"
    with open(path, "w") as f:
        json.dump(table, f)
    print("✓ cached →", path)


# ───────────────────── run ───────────────────────────────────────────────────
ds = load_dataset("iamgroot42/mimir", domain_name,
                  split=split_name, token=hf_token)
members    = ds["member"]   [:num_samples]
nonmembers = ds["nonmember"][:num_samples]

build_cache(members,    "member")
build_cache(nonmembers, "nonmember")

del mlm, lm; torch.cuda.empty_cache()
print("Neighbour generation (loss-top-k heuristic) completed.")

In [4]:
###############################################################################
# Cell 2.5-CEpswap – Neighbour generation with CEα × pswap score + batching  #
###############################################################################
"""
One forward pass through the causal-LM (GPU-0) gives the CE vector.
We then mask B positions together on the MLM (GPU-1/CPU) – default B=8.
This reduces the MLM cost by ≈ B ×.

Output:
    cache3/neigh3_<domain>_<split>_<tag>.json
Neighbours are stored in *descending* score order so that Cell 6 can keep
only the first K if it wants.
"""
# ──────────────── user knobs ────────────────────────────────────────────────
domain_name   = "arxiv"
split_name    = "ngram_7_0.2"
num_samples   = 1_000
hf_token      = "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"

SEARCH_MODEL  = "bert"          # "bert" | "distilbert" | "roberta"
NEI_K         = 100             # neighbours per passage
ALPHA         = 1.0             # CE exponent
BATCH_POS     = 8               # ← number of positions masked together
RNG_SEED      = 0
cache_dir     = "cache3" ; os.makedirs(cache_dir, exist_ok=True)

# ─────────────── libraries & models (unchanged on the outside) ──────────────
import os, json, math, random, torch, numpy as np, itertools
from tqdm.auto import tqdm
from datasets import load_dataset
from transformers import (
    BertForMaskedLM, BertTokenizer,
    DistilBertForMaskedLM, DistilBertTokenizer,
    RobertaForMaskedLM, RobertaTokenizer,
    AutoModelForCausalLM, AutoTokenizer,
)
torch.manual_seed(RNG_SEED); np.random.seed(RNG_SEED); random.seed(RNG_SEED)

suite,size,dedup = "Pythia","70M",True
cam_name  = get_model_name(suite,size,dedup)                 # helper comes
tok_lm    = AutoTokenizer.from_pretrained(cam_name)          # from your utils
tok_lm.add_special_tokens({'pad_token':'[PAD]'})
lm = (AutoModelForCausalLM
      .from_pretrained(cam_name, torch_dtype=torch.float16,
                       low_cpu_mem_usage=True)
      .to("cuda:0").eval())

if SEARCH_MODEL == "bert":
    tok_mlm = BertTokenizer.from_pretrained("bert-base-uncased")
    mlm     = BertForMaskedLM.from_pretrained("bert-base-uncased")
elif SEARCH_MODEL == "distilbert":
    tok_mlm = DistilBertTokenizer.from_pretrained("distilbert-base-uncased")
    mlm     = DistilBertForMaskedLM.from_pretrained("distilbert-base-uncased")
else:
    tok_mlm = RobertaTokenizer.from_pretrained("roberta-base")
    mlm     = RobertaForMaskedLM.from_pretrained("roberta-base")

DEV_MLM   = "cuda:1" if torch.cuda.device_count() > 1 else "cpu"
tok_mlm.model_max_length = 512
mlm = mlm.to(DEV_MLM).eval()
MASK_ID   = tok_mlm.mask_token_id
drop      = torch.nn.Dropout(p=0.7)

# ───────────── CE once per passage ──────────────────────────────────────────
@torch.no_grad()
def token_CE(text: str, max_len: int = 1024):
    enc = tok_lm(text, return_tensors="pt",
                 truncation=True, max_length=max_len).to(lm.device)
    logits = lm(enc.input_ids, labels=enc.input_ids).logits[:, :-1]  # (1,L-1,V)
    tgt    = enc.input_ids[:, 1:]
    ce = torch.nn.functional.cross_entropy(
            logits.reshape(-1, logits.size(-1)),
            tgt.reshape(-1), reduction="none").view(tgt.size())
    mask = tgt.ne(tok_lm.pad_token_id)
    return ce[mask].cpu().tolist()          # list length = # real tokens

# ───────────── pswap for a *batch* of positions ─────────────────────────────
@torch.no_grad()
def pswap_batch(ids: torch.Tensor, pos_batch):
    """
    ids:  1-D tensor of token-ids, length L
    pos_batch: iterable[int] of positions to evaluate together
    Returns dict { position → list[(tid, pswap)] } (top-5 substitutes each)
    """
    L = ids.size(0)
    B = len(pos_batch)
    # ---- build (B,L) copy where row b has dropout at pos_batch[b] ----------
    ids_rep = ids.unsqueeze(0).repeat(B, 1)                # (B,L)
    # manual embedding path to skip encoder repetition
    if SEARCH_MODEL == "roberta":
        embs = mlm.roberta.embeddings(ids_rep)
    elif SEARCH_MODEL == "distilbert":
        embs = mlm.distilbert.embeddings(ids_rep)
    else:  # bert
        embs = mlm.bert.embeddings(ids_rep)
    for b,p in enumerate(pos_batch):
        embs[b, p, :] = drop(embs[b, p, :])
    logits = mlm(inputs_embeds=embs.to(DEV_MLM)).logits     # (B,L,V)
    out = {}
    for b,p in enumerate(pos_batch):
        probs  = torch.softmax(logits[b, p], dim=-1)
        orig_t = ids[p]
        p_orig = probs[orig_t].item()
        top_p, top_t = torch.topk(probs, 6)                 # keep 5 alt
        cand = []
        for q,tid in zip(top_p, top_t):
            tid = tid.item()
            if tid == orig_t: continue
            pswap = q.item() / (1 - p_orig + 1e-12)
            cand.append((tid, pswap))
        out[p] = cand
    return out

# ───────────── neighbours for one passage (uses batching) ───────────────────
@torch.no_grad()
def neighbours_for_text(text: str, k: int = NEI_K,
                        alpha: float = ALPHA, B: int = BATCH_POS):
    ce_vec   = token_CE(text)                 # CPU list – length L₁
    ids_mlm  = tok_mlm(text, return_tensors="pt").to(DEV_MLM).input_ids[0]
    L_mlm    = ids_mlm.size(0)

    cand2score = {}
    positions  = list(range(1, min(len(ce_vec)+1, L_mlm-1)))  # 1 … L-2
    for chunk in (positions[i:i+B] for i in range(0, len(positions), B)):
        sub = pswap_batch(ids_mlm, chunk)
        for p, items in sub.items():
            ce_a = ce_vec[p-1] ** alpha
            for tid, ps in items:
                cand2score[(p, tid)] = ps * ce_a

    best = sorted(cand2score.items(),
                  key=lambda kv: kv[1], reverse=True)[:k]
    ids_np = ids_mlm.cpu().numpy()
    neigh  = []
    for (pos, tid), _ in best:
        new_ids = ids_np.copy(); new_ids[pos] = tid
        neigh.append(tok_mlm.decode(new_ids, skip_special_tokens=True))

    neigh = list(dict.fromkeys(neigh))[:k]   # dedup & pad
    neigh += [text]*(k-len(neigh))
    return neigh

# ───────────── cache builder ────────────────────────────────────────────────
def build_cache(passages, tag):
    table = [neighbours_for_text(t) for t in tqdm(passages,
              desc=f"{tag} neighbours (CEα×pswap,B={BATCH_POS})")]
    path  = f"{cache_dir}/neigh3_{domain_name}_{split_name}_{tag}.json"
    json.dump(table, open(path,"w"));  print("✓ cached →", path)

ds = load_dataset("iamgroot42/mimir", domain_name,
                  split=split_name, token=hf_token)
build_cache(ds["member"][:num_samples],    "member")
build_cache(ds["nonmember"][:num_samples], "nonmember")

del mlm, lm; torch.cuda.empty_cache()
print("Neighbour generation completed.")

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForMaskedLM: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'cls.seq_relationship.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

member neighbours (CEα×pswap,B=8):   0%|          | 0/500 [00:00<?, ?it/s]

KeyboardInterrupt:

In [4]:
###############################################################################
# Cell 3 – Signal helpers  (COMPLETE, drop-in)                                 #
###############################################################################
import math, random, numpy as np, torch, torch.nn as nn
from itertools import islice
from transformers import AutoModelForSeq2SeqLM, AutoTokenizer
from contextlib import nullcontext
from torch import amp

# ───── utility ───────────────────────────────────────────────────────────────
safe_mean = lambda arr: float(np.mean(arr)) if len(arr) else 0.0
_diff     = lambda a,b: a-b if np.isfinite(a) and np.isfinite(b) else 0.0

# ──────────────────── NEW: read neighbour JSON cache ────────────────────────
# ─────────── Cell-3: fix _load_cached_neighbours padding ────────────
def _load_cached_neighbours(domain, split, tag):
    """
    Return list[list[str]] with each inner list length == C.NEI_K.
    If C.NEI_K == 0 → None (skip neighbours).
    """
    if C.NEI_K == 0:
        return None

    path = f"cache/neigh_{domain}_{split}_{tag}.json"
    with open(path) as f:
        table = json.load(f)           # list of neighbour lists

    # ---- guarantee len(row) == C.NEI_K  --------------------------------
    for i,row in enumerate(table):
        if len(row) >= C.NEI_K:
            table[i] = row[:C.NEI_K]
        else:                          # pad by repeating first neighbour
            table[i] = row + row[:1] * (C.NEI_K - len(row))
    # --------------------------------------------------------------------
    return table

def _count_below(seq, thr, Tprime):
    sub = seq if Tprime is None else seq[:Tprime]
    return sum(v<=thr for v in sub)/len(sub) if sub else 0.0

def _count_below_mean(seq, L=None):
    sl = seq if L is None else seq[:L]
    if not sl: return 0.0
    m = safe_mean(sl)
    return sum(v<=m for v in sl)/len(sl)

def _count_below_prev_mean(seq, L=None):
    sl = seq if L is None else seq[:L]
    if len(sl)<=1: return 0.0
    below, csum = 0, sl[0]
    for i,v in enumerate(sl[1:],1):
        below += v<=csum/i
        csum  += v
    return below/(len(sl)-1)

def _lz_complexity(seq,bins,Tprime):
    sub = seq if Tprime is None else seq[:Tprime]
    if not sub: return 0.0
    arr = np.asarray(sub); lo,hi = arr.min(),arr.max()
    if hi-lo<1e-12: return 1.0
    edges   = np.linspace(lo,hi+1e-9,bins)
    symbols = ''.join(chr(65+np.digitize(v,edges)) for v in arr)
    i,c = 0,1
    while i<len(symbols)-1:
        l=1
        while symbols[i:i+l] in symbols[:i] and i+l<len(symbols): l+=1
        i+=l; c+=1
    return float(c)

# --- fix 6 ------------------------------------------------------
def _replicate_if_short(seq, desired):
    """
    Repeat the *prefix* of the loss sequence so that the first tokens
    (which correspond to the repeated text) are duplicated, matching
    Sec 3.2.2's ‘repeat-the-passage’ rule.
    """
    if not seq or len(seq) >= desired:
        return seq
    out = list(seq)
    while len(out) < desired:
        take = min(len(seq), desired - len(out))
        out.extend(seq[:take])                 # copy prefix again
    return out


def _slope_signal(loss_seq, Tprime):
    """OLS slope of the first T′ points (Eq.(6) in the paper)."""
    if not loss_seq:
        return 0.0
    y = np.asarray(_replicate_if_short(loss_seq, Tprime)[:Tprime])
    x = np.arange(len(y))
    var = np.mean((x - x.mean()) ** 2)
    if var == 0:
        return 0.0
    cov = np.mean((x - x.mean()) * (y - y.mean()))
    return float(cov / var)

def _approximate_entropy(loss_seq, Tprime, m=8, r=0.8):
    """
    ApEn as defined in Appendix A (same default params as the paper).
    Smaller ⇒ more regular ⇒ more likely a *member*.
    """
    seq = _replicate_if_short(loss_seq, Tprime)[:Tprime]
    if len(seq) < m + 2:
        return 0.0
    vals = np.asarray(seq)

    def _phi(mm):
        N = len(vals) - mm + 1
        if N <= 0:
            return 0.0
        patterns = np.array([vals[i : i + mm] for i in range(N)])
        C = (
            np.sum(
                np.max(np.abs(patterns[:, None] - patterns[None, :]), axis=2)
                <= r,
                axis=0,
            )
            / N
        )
        return np.mean(np.log(C + 1e-12))

    return float(_phi(m) - _phi(m + 1))

def token_diversity(text, tokenizer):
    toks = tokenizer.tokenize(text)
    return len(set(toks)) / len(toks) if toks else 0.0

# ───── CE-loss helper (GPU) ──────────────────────────────────────────────────
@torch.no_grad()
def _ce_losses(texts, model, tok, max_len=1024):
    if not texts: return []
    enc = tok(texts, return_tensors="pt", padding=True,
              truncation=True,max_length=max_len).to(model.device)
    ctx = amp.autocast(device_type="cuda") if C.fp16_ce else nullcontext()
    with ctx:
        out = model(enc.input_ids, labels=enc.input_ids,
                    attention_mask=enc.attention_mask)
    logits  = out.logits[:,:-1]; tgt = enc.input_ids[:,1:]
    mask    = enc.attention_mask[:,1:]
    lossfn  = nn.CrossEntropyLoss(reduction="none")
    flat    = lossfn(logits.reshape(-1,logits.size(-1)), tgt.reshape(-1))
    flat    = flat.view(logits.size(0),-1)
    return [flat[i,:int(mask[i].sum())].tolist() for i in range(len(texts))]

# ───── neighbour “score only” helper  (uses cached texts)  ──────────────────
def _nei_ce_losses(nei_batch, model, tok, max_len, stream_bs):
    """Return list[float] mean-CE for each neighbour text in `nei_batch`."""
    out = []
    for j in range(0, len(nei_batch), stream_bs):
        out.extend(
            _ce_losses(nei_batch[j : j + stream_bs],
                       model, tok, max_len=max_len)
        )
        torch.cuda.empty_cache()
    return [safe_mean(v) for v in out]          # one scalar per neighbour

# ──────────────────────────────────────────────────────────────────────────
# Neighbour-delta helper  (vectorised – fast)
# ──────────────────────────────────────────────────────────────────────────
# ---------------------------------------------------------------------------
# (Cell-3)  memory-robust mean-CE for many texts  –> 1 × float per input
# ---------------------------------------------------------------------------
# -----------------------------------------------------------------------
# Memory-robust mean-CE for many texts   →   np.ndarray, shape (N,)
# -----------------------------------------------------------------------
@torch.no_grad()
def _batched_mean_ce(texts,
                     model,
                     tok,
                     bs: int = 4,                       # safe default
                     max_len: int = C.MAX_LEN_CE):

    # -------- canonicalise input to a *list[str]* ----------------------
    if isinstance(texts, np.ndarray):
        texts = texts.tolist()
    if isinstance(texts, str):
        texts = [texts]
    else:
        texts = [str(t) for t in texts]

    device_orig = next(model.parameters()).device
    use_gpu     = device_orig.type == "cuda"

    # -------- inner helper that handles one mini-batch -----------------
    def _run_chunk(chunk_txts):
        """
        Return a *list* with one mean-CE scalar per text in `chunk_txts`.
        Works on whatever device `model` is currently on.
        """
        # reuse the generic helper ⇒ list[list[token-loss]]
        seq_losses = _ce_losses(
            chunk_txts,          # the texts
            model,               # same model
            tok,                 # same tokenizer
            max_len=max_len
        )
        # collapse every token-loss sequence → single float
        return [safe_mean(sl) for sl in seq_losses]     # len == len(chunk_txts)

    # -------- adaptive loop over the entire list -----------------------
    losses, i = [], 0
    while i < len(texts):
        cur_bs = min(bs, len(texts) - i)
        while True:
            try:
                losses.extend(_run_chunk(texts[i:i+cur_bs]))
                torch.cuda.empty_cache()
                break
            except RuntimeError as e:
                if "CUDA out of memory" in str(e) and cur_bs > 1:
                    cur_bs //= 2                           # halve & retry
                    torch.cuda.empty_cache()
                    continue
                elif use_gpu:                              # final GPU→CPU
                    print("⚠  OOM persists – switching neighbour-CE to CPU")
                    model_cpu = model.to("cpu")
                    losses.extend(_run_chunk(texts[i:i+cur_bs]))
                    model.to(device_orig)
                    use_gpu = False
                    break
                else:
                    raise
        i += cur_bs

    return np.asarray(losses, dtype=np.float32)


def add_nei_delta(base_dicts, neighbour_table, K, model, tokenizer):
    """
    Add one scalar feature  ‘nei_delta’  to every dict in `base_dicts`.
    nei_delta =  CE(original passage)  −  mean CE(K neighbours)
    """
    if K == 0 or neighbour_table is None:
        return base_dicts          # nothing to do

    # --- keep 1-to-1 alignment ------------------------------------------------
    neighbour_table = neighbour_table[:len(base_dicts)]
    if len(neighbour_table) < len(base_dicts):          # unlikely
        neighbour_table.extend(neighbour_table[: len(base_dicts)-len(neighbour_table)])

    # --- CE for all neighbours (flat list) -----------------------------------
    flat_nei = list(itertools.chain.from_iterable(row[:K] for row in neighbour_table))
    nei_ce   = _batched_mean_ce(flat_nei, model, tokenizer).reshape(len(base_dicts), K)

    # --- build new dicts ------------------------------------------------------
    out = []
    for d, nloss in zip(base_dicts, nei_ce):
        new_d = d.copy()
        base_ce = float(np.mean(d["loss_seq_orig"]))    # always stored
        new_d["nei_delta"] = base_ce - float(nloss.mean())
        out.append(new_d)
    return out

# ───── main per-batch extractor (FINAL, memory-safe) ────────────────────────
@torch.no_grad()
def gather_signals_for_batch(
        texts, model, tokenizer,
        max_length=1024, store_full_sequences=True,
        stream_bs=32,
        neighbour_texts=None,          # ← new (list[list[str]] or None)
):
    tok, max_len = tokenizer, min(max_length, C.MAX_LEN_CE)

    # ------------------------------------------------------------------ #
    # 1) build the 9 text variants                                       #
    # ------------------------------------------------------------------ #
    variants = {(t, r): [] for t in ("T", "200", "300") for r in (0, 1, 2)}

    def _reps(txt, tp):
        if tp is None:
            base = txt
        else:
            ids = tok(txt)["input_ids"][:tp]
            base = tok.decode(ids, skip_special_tokens=True)
        return base, f"{base} {base}", f"{base} {base} {base}"

    for t in texts:
        for tag, tp in (("T", None), ("200", 200), ("300", 300)):
            variants[(tag, 0)].append(_reps(t, tp)[0])
            variants[(tag, 1)].append(_reps(t, tp)[1])
            variants[(tag, 2)].append(_reps(t, tp)[2])

    # helper that slices a list into ≤ stream_bs chunks and calls _ce_losses
    def _ce_stream(seq_list):
        out = []
        for j in range(0, len(seq_list), stream_bs):
            out.extend(_ce_losses(seq_list[j : j + stream_bs],
                                  model, tok, max_len=max_len))
            torch.cuda.empty_cache()
        return out

    losses = {k: _ce_stream(v) for k, v in variants.items()}

    # ------------------------------------------------------------------ #
    # 2) build feature dicts ------------------------------------------- #
    # ------------------------------------------------------------------ #
    feats = []
    for i, orig in enumerate(texts):
        L = lambda tag, rp: losses[(tag, rp)][i]   # bind i to helper
        f = {}                                     # ← one passage dict

        # ── ❶ cut / cal / ppl / calppl families ────────────────────────
        for tag, tp in C.CUT_TPRIMES.items():
            # token-diversity for *this* truncation
            if tp is None:
                txt_trim = orig
            else:
                ids_trim = tok(orig)["input_ids"][:tp]
                txt_trim = tok.decode(ids_trim, skip_special_tokens=True)
            div_tag = max(token_diversity(txt_trim, tok), 1e-12)

            lb, lr1, lr2 = L(tag, 0), L(tag, 1), L(tag, 2)
            for fam, post in (
                ("cut",    lambda x: x),
                ("cal",    lambda x: x / div_tag),
                ("ppl",    lambda x: math.exp(x)),
                ("calppl", lambda x: math.exp(x) / div_tag),
            ):
                vb, vr1, vr2 = map(post, map(safe_mean, (lb, lr1, lr2)))
                f[f"{fam}_{tag}"]           = vb
                f[f"{fam}_{tag}_rep1_diff"] = _diff(vb, vr1)
                f[f"{fam}_{tag}_rep2_diff"] = _diff(vb, vr2)

        # ────────── ❷ count-below-CONST  (invert) ───────────────────────
        for tau in C.CB_TAU_LIST:
            lb, lr1, lr2 = L("200", 0), L("200", 1), L("200", 2)
            b, r1, r2    = (_count_below(x, tau, 200) for x in (lb, lr1, lr2))
            b, r1, r2 = (1.0 - b, 1.0 - r1, 1.0 - r2)
            k = f"cb_const{tau}"
            f[k] = b
            f[f"{k}_rep1_diff"] = _diff(b, r1)
            f[f"{k}_rep2_diff"] = _diff(b, r2)

        # ────────── ❸ count-below-MEAN (invert) ─────────────────────────
        for tag in C.CUT_TPRIMES:
            lb, lr1, lr2 = L(tag, 0), L(tag, 1), L(tag, 2)
            base = _count_below_mean(lb); r1 = _count_below_mean(lr1); r2 = _count_below_mean(lr2)
            base, r1, r2 = (1.0 - base, 1.0 - r1, 1.0 - r2)
            k = f"cbm_{tag}"
            f[k] = base
            f[f"{k}_rep1_diff"] = _diff(base, r1)
            f[f"{k}_rep2_diff"] = _diff(base, r2)
            # previous-mean
            f[f"cbpm_{tag}"] = 1.0 - _count_below_prev_mean(lb)

        # ────────── ❹ LZ, slope, ApEn ───────────────────────────────────
        for bins in C.LZ_BIN_LIST:
            lb, lr1, lr2 = L("200", 0), L("200", 1), L("200", 2)
            b, r1, r2 = (_lz_complexity(x, bins, 200) for x in (lb, lr1, lr2))
            k = f"lz_bins{bins}"
            f[k] = b
            f[f"{k}_rep1_diff"] = _diff(b, r1)
            f[f"{k}_rep2_diff"] = _diff(b, r2)

        # ────────── ❺ neighbour delta  (orig – neigh) ───────────────────
        if C.NEI_K > 0 and neighbour_texts is not None:
            nei_loss = _nei_ce_losses(neighbour_texts[i], model, tok,
                                      max_len=max_len, stream_bs=stream_bs)
            f["nei_delta"] = safe_mean(L("T", 0)) - safe_mean(nei_loss)
            if C.STORE_FULL_SEQ:
                f["nei_texts"] = list(neighbour_texts[i])

        # Slope & ApEn extra signals
        lb_full = L("T", 0)
        for tp in C.SLOPE_TPRIMES:
            f[f"slope_{tp}"] = -_slope_signal(lb_full, tp)
        for tp in C.APEN_TPRIMES:
            f[f"apen_{tp}"] = -_approximate_entropy(lb_full, tp)

        # optional raw sequence
        if store_full_sequences:
            f["loss_seq_orig"] = lb_full

        feats.append(f)

    return feats

def gather_signals_for_dataset(texts, model, tokenizer, *, tag, # "member" | "nonmember"
                               max_length=1024, batch_size=8):
    """
    Slice `texts` into mini-batches and call `gather_signals_for_batch`
    on each of them.  (The helper itself stays on the model’s current
    device, so no explicit `device` needs to be forwarded.)
    """
    
    all_dicts = []
    # load the *full* neighbour table once
    nei_table = (_load_cached_neighbours(domain_name, split_name, tag)
                 if C.NEI_K > 0 else None)
    for start in tqdm(range(0, len(texts), batch_size), desc="Signal-extraction"):
        end   = start + batch_size
        batch = texts[start:end]
        all_dicts.extend(
            gather_signals_for_batch(          # ← delete `device=` here
                batch, model, tokenizer,
                max_length=max_length,
                store_full_sequences=True,
                neighbour_texts = None if nei_table is None else nei_table[start:end]
            )
        )
        torch.cuda.empty_cache()
    return all_dicts

In [45]:
###############################################################################
# Cell 4 – Combiners & attack models (Section 4)
###############################################################################

import numpy as np
import pandas as pd
from collections import defaultdict
from math import log
from sklearn.decomposition import PCA
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score, roc_curve

# ---------------------------------------------------------------------------
# 1) p-value combiners (Edgington + variants)
# ---------------------------------------------------------------------------
_CLIP = 1e-5

def _pvalue(value, arr):
    n    = arr.size
    rank = np.searchsorted(arr, value, side="right")
    return rank / (n + 1)

def combine_pvalues(pvals, method="edgington"):
    clip = lambda p: min(max(p, _CLIP), 1 - _CLIP)
    if method == "edgington":
        return sum(pvals)
    if method == "fisher":
        return -2.0 * sum(log(clip(p)) for p in pvals)
    if method == "pearson":
        return -2.0 * sum(log(clip(1-p)) for p in pvals)
    if method == "george":
        return     sum(log(clip(p)/(1-clip(p))) for p in pvals)
    raise ValueError(method)

def pv_score_batch(dicts, ref, method="edgington"):
    scores = []
    for d in dicts:
        pvals = []
        for k,v in d.items():
            if k not in ref: 
                continue
            if k == "nei_delta":
                # repeat the neighbour p-value C.NEI_WEIGHT times
                pvals.extend([_pvalue(v, ref[k])] * C.NEI_WEIGHT)
            else:
                pvals.append(_pvalue(v, ref[k]))
        scores.append(combine_pvalues(pvals, method))
    return scores

def edgington_fit(nonms):
    ref = defaultdict(list)
    for d in nonms:
        for k,v in d.items():
            if isinstance(v,(int,float)) and np.isfinite(v):
                ref[k].append(v)
    for k, arr in ref.items():
        ref[k] = np.sort(np.asarray(arr, dtype=np.float32))
    return ref

# ---------------------------------------------------------------------------
# 2) Group-PCA + Logistic Regression attack
# ---------------------------------------------------------------------------
PCA_DIM_PER_GROUP = 2  # user may override before calling logistic_fit

def logistic_fit(member_dicts, nonmember_dicts):
    # 1) Combine data + labels
    Xd = member_dicts + nonmember_dicts
    y  = np.array([1]*len(member_dicts) + [0]*len(nonmember_dicts))

    # 2) Extract numeric features
    keys = sorted({
        k for d in Xd for k,v in d.items()
        if isinstance(v,(int,float)) and np.isfinite(v)
    })
    raw = np.array([[d.get(k,0.0) for k in keys] for d in Xd],
                   dtype=np.float32)

    # 3) Global standardization
    mu    = raw.mean(axis=0)
    sigma = raw.std(axis=0) + 1e-9
    raw_z = (raw - mu) / sigma

    # 4) Group split
    grp2idx   = defaultdict(list)
    for i,k in enumerate(keys):
        grp2idx[_group_name(k)].append(i)

    # 5) Per-group PCA (no whitening)
    pca_dict    = {}
    transformed = []
    for g,cols in grp2idx.items():
        sub = raw_z[:, cols]
        if sub.shape[1] == 1:
            pca_dict[g] = None
            transformed.append(sub)
        else:
            p = PCA(n_components=min(PCA_DIM_PER_GROUP, sub.shape[1]))
            p.fit(sub)
            pca_dict[g] = p
            transformed.append(p.transform(sub))

    # 6) Concatenate all group outputs
    X = np.concatenate(transformed, axis=1)

    # ←———   **BOOST THE NEIGHBOUR BLOCK BY NEI_GAMMA**   ←———  
    gamma = globals().get('NEI_GAMMA', 1.0)
    if 'nei' in grp2idx and gamma != 1.0:
        start = 0
        for grp,cols in grp2idx.items():
            dim = 1 if pca_dict[grp] is None else min(PCA_DIM_PER_GROUP,len(cols))
            if grp == 'nei':
                X[:, start:start+dim] *= gamma
                break
            start += dim

    # 7) Fit logistic regression
    clf = LogisticRegression(max_iter=1000, solver="lbfgs").fit(X, y)

    # 8) Store metadata *exactly* as before
    final_groups = []
    for g,cols in grp2idx.items():
        dim = 1 if pca_dict[g] is None else min(PCA_DIM_PER_GROUP, len(cols))
        final_groups.extend([g]*dim)

    return clf, {
        "keys":                keys,
        "grp2idx":             grp2idx,
        "pca":                 pca_dict,
        "mu":                  mu,
        "sigma":               sigma,
        "final_feature_groups":final_groups,
        "nei_gamma":           gamma
    }

def logistic_score_batch(dicts, clf, meta):
    # 1) Rebuild raw + global z
    keys  = meta["keys"]
    raw   = np.array([[d.get(k,0.0) for k in keys] for d in dicts],
                     dtype=np.float32)
    raw_z = (raw - meta["mu"]) / meta["sigma"]

    # 2) Per-group PCA projections
    pcs_parts = []
    for g,cols in meta["grp2idx"].items():
        sub = raw_z[:, cols]
        p   = meta["pca"][g]
        pcs = sub if p is None else p.transform(sub)
        pcs_parts.append(pcs)

    # 3) Concatenate all group‐PCs
    Xq = np.concatenate(pcs_parts, axis=1)

    # 4) BOOST the neighbour block again
    gamma = meta.get("nei_gamma", 1.0)
    if 'nei' in meta["grp2idx"] and gamma != 1.0:
        start = 0
        for grp,cols in meta["grp2idx"].items():
            dim = 1 if meta["pca"][grp] is None else min(PCA_DIM_PER_GROUP, len(cols))
            if grp == 'nei':
                Xq[:, start:start+dim] *= gamma
                break
            start += dim

    # 5) Return -P(member) exactly as before
    return -clf.predict_proba(Xq)[:, 1]

In [51]:
###############################################################################
# ALTERNATIVE Cell 4 – Combiners & attack models (Section 4)  [Whitened Group-PCA]
###############################################################################

import numpy as np
import pandas as pd
from collections import defaultdict
from math import log
from sklearn.decomposition import PCA
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score, roc_curve

# ──────────────────── 1) p-value combiners (unchanged) ──────────────────────
_CLIP = 1e-5

def _pvalue(value, arr):
    n    = arr.size
    rank = np.searchsorted(arr, value, side="right")
    return rank / (n + 1)

def combine_pvalues(pvals, method="edgington"):
    clip = lambda p: min(max(p, _CLIP), 1 - _CLIP)
    if method == "edgington":
        return sum(pvals)
    if method == "fisher":
        return -2.0 * sum(log(clip(p)) for p in pvals)
    if method == "pearson":
        return -2.0 * sum(log(clip(1-p)) for p in pvals)
    if method == "george":
        return sum(log(clip(p)/(1-clip(p))) for p in pvals)
    raise ValueError(f"unknown combiner: {method}")

def edgington_fit(nonms):
    ref = defaultdict(list)
    for d in nonms:
        for k,v in d.items():
            if isinstance(v,(int,float)) and np.isfinite(v):
                ref[k].append(v)
    for k,arr in ref.items():
        ref[k] = np.sort(np.asarray(arr, dtype=np.float32))
    return ref

def pv_score_batch(dicts, ref, method="edgington"):
    scores = []
    for d in dicts:
        pvals = []
        for k,v in d.items():
            if k not in ref:
                continue
            if k == "nei_delta":
                pvals.extend([_pvalue(v, ref[k])] * C.NEI_WEIGHT)
            else:
                pvals.append(_pvalue(v, ref[k]))
        scores.append(combine_pvalues(pvals, method))
    return scores

# ──────────────────── 2) Whitened Group-PCA + Logistic Regression ───────────

PCA_DIM_PER_GROUP = 2   # max PCs per group
NEI_GAMMA         = 1.0 # overwritten in Cell 6’s driver

def _group_name(k: str) -> str:
    if k.startswith("nei"):    
        return "nei"
    for prefix in (
        "cut","calppl","ppl","cal",
        "cb_const","cbm","cbpm",
        "lz_bins","slope","apen"
    ):
        if k.startswith(prefix):
            return prefix.split('_')[0]
    return "misc"

def logistic_fit(member_dicts, nonmember_dicts):
    # 1) stack + labels
    Xd = member_dicts + nonmember_dicts
    y  = np.array([1]*len(member_dicts) + [0]*len(nonmember_dicts), dtype=int)

    # 2) raw numeric matrix
    keys = sorted(
        k for d in Xd for k,v in d.items()
        if isinstance(v,(int,float)) and np.isfinite(v)
    )
    raw = np.array([[d.get(k,0.0) for k in keys] for d in Xd], dtype=np.float32)

    # 3) global z-score
    mu    = raw.mean(axis=0)
    sigma = raw.std (axis=0) + 1e-9
    raw_z = (raw - mu) / sigma

    # 4) per-group PCA with whitening
    grp2idx    = defaultdict(list)
    pca_dict   = {}
    pcs_parts  = []
    group_dims = []

    for i,k in enumerate(keys):
        grp2idx[_group_name(k)].append(i)

    for g, cols in grp2idx.items():
        sub = raw_z[:, cols]
        if sub.shape[1] == 1:
            pca_dict[g] = None
            pcs = sub
        else:
            p = PCA(n_components=min(PCA_DIM_PER_GROUP, sub.shape[1]),
                    whiten=True)    # ← whitening ensures each PC has unit variance
            pcs = p.fit_transform(sub)
            pca_dict[g] = p
        pcs_parts.append(pcs)
        group_dims.append((g, pcs.shape[1]))

    # 5) concatenate all group-PCs
    X = np.concatenate(pcs_parts, axis=1)

    # 6) boost ‘nei’ block by NEI_GAMMA
    gamma = globals().get("NEI_GAMMA", 1.0)
    if 'nei' in grp2idx and gamma != 1.0:
        start = 0
        for grp, dim in group_dims:
            if grp == 'nei':
                X[:, start:start+dim] *= gamma
                break
            start += dim

    # 7) fit logistic regression
    clf = LogisticRegression(max_iter=1000, solver="lbfgs").fit(X, y)

    # 8) store metadata for scoring
    return clf, {
        'keys':       keys,
        'grp2idx':    grp2idx,
        'pca':        pca_dict,
        'mu':         mu,
        'sigma':      sigma,
        'group_dims': group_dims,
        'nei_gamma':  gamma
    }

def logistic_score_batch(dicts, clf, meta):
    # 1) rebuild + global z
    raw   = np.array([[d.get(k,0.0) for k in meta['keys']] for d in dicts],
                     dtype=np.float32)
    raw_z = (raw - meta['mu']) / meta['sigma']

    # 2) apply each group’s PCA
    pcs_parts = []
    for g, cols in meta['grp2idx'].items():
        sub = raw_z[:, cols]
        p   = meta['pca'][g]
        pcs = sub if p is None else p.transform(sub)
        pcs_parts.append(pcs)

    # 3) concat + boost ‘nei’
    Xq    = np.concatenate(pcs_parts, axis=1)
    gamma = meta['nei_gamma']
    if 'nei' in meta['grp2idx'] and gamma != 1.0:
        start = 0
        for grp, dim in meta['group_dims']:
            if grp == 'nei':
                Xq[:, start:start+dim] *= gamma
                break
            start += dim

    # 4) return -P(member)
    return -clf.predict_proba(Xq)[:, 1]

In [6]:
###############################################################################
# Cell 5 – Utility for ROC metrics + quick plots                               #
###############################################################################

def compute_metrics_and_show(member_scores, nonmember_scores, *, show=True):
    y = np.array([1]*len(member_scores) + [0]*len(nonmember_scores))
    s = -np.concatenate([member_scores, nonmember_scores])  # invert for ROC
    auc = roc_auc_score(y, s)
    fpr, tpr, _ = roc_curve(y, s)
    tpr_at_1 = tpr[np.argmin(np.abs(fpr - 0.01))]
    if show:
        plt.plot(fpr, tpr, label=f"AUC={auc:.3f}")
        plt.xlabel("FPR"); plt.ylabel("TPR"); plt.title("ROC curve"); plt.legend(); plt.show()
    print(f"AUC={auc:.4f}  |  TPR@1%FPR={tpr_at_1*100:.2f}%")
    return auc, tpr_at_1

In [72]:
###############################################################################
# Cell 6 – Grid-search driver: CAMIA  +  Neighbourhood Comparison
###############################################################################
import os, json, pandas as pd, numpy as np, itertools, time
from sklearn.metrics import roc_auc_score, roc_curve
from accelerate import Accelerator

# ------------------------ experiment grid ------------------------------------
GRID_NEI_K      = [0, 25, 100]          # 1× “vanilla CAMIA” + 2× with neighbours
GRID_NEI_WEIGHT = [9, 18, 36, 72]       # ⧺ (ignored when K == 0)
GRID_NEI_GAMMA  = [1,  2,  3,  4]       # zipped to weights
N_RUNS          = 10                    # per (K,W) point
OUT_PARENT      = "experiment_whiten"

# ------------------------ static model / data conf ---------------------------
domain_name  = "hackernews"
split_name   = "ngram_7_0.2"
num_samples  = 1000
suite,size,dedup = "Pythia","70M",True
model_tag    = f"{suite}{size}{'-dedup' if dedup else ''}".lower()

my_hf_token  = "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"
ds           = load_dataset("iamgroot42/mimir", domain_name,
                            split=split_name, token=my_hf_token)
num_samples  = min(num_samples, len(ds["member"]))
all_members  = ds["member"][:num_samples]
all_nonmem   = ds["nonmember"][:num_samples]

model_name   = get_model_name(suite,size,dedup)
tokenizer    = AutoTokenizer.from_pretrained(model_name)
tokenizer.add_special_tokens({'pad_token':'[PAD]'})
acc          = Accelerator()
model        = AutoModelForCausalLM.from_pretrained(
                  model_name, torch_dtype=torch.float16, low_cpu_mem_usage=True
               )
model        = acc.prepare(model).eval()

# ───────────────────────── helpers ───────────────────────────────────────────
def _auc_tpr01(pos, neg):
    y   = [1]*len(pos) + [0]*len(neg)
    s   = -np.concatenate([pos, neg])
    fpr, tpr, _ = roc_curve(y, s)
    return roc_auc_score(y, s), tpr[np.argmin(np.abs(fpr-0.01))]

# one-off extraction at K=0
print("◆ Extracting CAMIA signals once (K=0)…")
C.NEI_K = 0
base_mem = gather_signals_for_dataset(all_members, model, tokenizer, tag="member",   batch_size=2)
base_non = gather_signals_for_dataset(all_nonmem,  model, tokenizer, tag="nonmember",batch_size=2)
print(f"◆   done  –  {len(base_mem)} mem + {len(base_non)} non-mem passages")

# outer scoreboard
best_metric = {}   # metric_name → (score, K, param)

# ───────────────────────── grid loop ─────────────────────────────────────────
for K in GRID_NEI_K:
    C.NEI_K = K

    # precompute neighbour-augmented dicts
    mem_sdicts = add_nei_delta(
        base_mem,
        _load_cached_neighbours(domain_name, split_name, "member"),
        K, model, tokenizer
    )
    non_sdicts = add_nei_delta(
        base_non,
        _load_cached_neighbours(domain_name, split_name, "nonmember"),
        K, model, tokenizer
    )

    # choose which W,GAM pairs to evaluate
    weight_list = GRID_NEI_WEIGHT if K else [0]
    gamma_list  = GRID_NEI_GAMMA  if K else [1.0]
    for W, GAM in zip(weight_list, gamma_list):
        C.NEI_WEIGHT = W
        NEI_GAMMA    = GAM

        print(f"◇ now evaluating  K={K}   W={W}   γ={GAM}")
        exp_dir = f"{OUT_PARENT}/{domain_name}_{model_tag}/K{K}_W{W}"
        os.makedirs(exp_dir, exist_ok=True)

        records = []
        for run in range(N_RUNS):
            run_tag = f"run_{run:02d}"
            run_dir = f"{exp_dir}/{run_tag}"
            os.makedirs(run_dir, exist_ok=True)

            # split indices
            rng        = np.random.default_rng(42 + run)
            idx_mem    = rng.permutation(num_samples)
            idx_non    = rng.permutation(num_samples)
            cut        = int(num_samples * 0.30)
            mem_cal_i, mem_test_i = idx_mem[:cut], idx_mem[cut:]
            non_cal_i, non_test_i = idx_non[:cut], idx_non[cut:]

            mem_cal_sd  = [mem_sdicts[i] for i in mem_cal_i]
            non_cal_sd  = [non_sdicts[i] for i in non_cal_i]
            mem_test_sd = [mem_sdicts[i] for i in mem_test_i]
            non_test_sd = [non_sdicts[i] for i in non_test_i]

            # Edgington‐combiner metrics
            ref_dict = edgington_fit(non_cal_sd)
            pv_auc, pv_tpr = {}, {}
            for m in ("fisher","pearson","george","edgington"):
                s_mem = pv_score_batch(mem_test_sd, ref_dict, m)
                s_non = pv_score_batch(non_test_sd, ref_dict, m)
                pv_auc[m], pv_tpr[m] = _auc_tpr01(s_mem, s_non)

            # Logistic + PCA metrics
            clf, meta    = logistic_fit(mem_cal_sd, non_cal_sd)
            s_mem_log    = logistic_score_batch(mem_test_sd, clf, meta)
            s_non_log    = logistic_score_batch(non_test_sd, clf, meta)
            auc_log, tpr_log = _auc_tpr01(s_mem_log, s_non_log)

            # per-run CSV with *all* signals
            rows = []
            for j,i in enumerate(mem_test_i):
                r = {"text_index":int(i), "membership_label":1, "set_split":"test"}
                r.update(mem_test_sd[j])
                rows.append(r)
            for j,i in enumerate(non_test_i):
                r = {"text_index":int(i), "membership_label":0, "set_split":"test"}
                r.update(non_test_sd[j])
                rows.append(r)
            pd.DataFrame(rows).to_csv(
                f"{run_dir}/results_{domain_name}_{model_tag}.csv", index=False
            )

            # per-run JSON summary (with nei_gamma)
            summary = {
                "model_tag":    model_tag,
                "domain":       domain_name,
                "nei_K":        K,
                "nei_weight":   W,
                "nei_gamma":    GAM,
                **{f"auc_{m}":   float(pv_auc[m])  for m in pv_auc},
                **{f"tpr01_{m}": float(pv_tpr[m])  for m in pv_tpr},
                "auc_log":      float(auc_log),
                "tpr01_log":    float(tpr_log)
            }
            with open(f"{run_dir}/summary_{domain_name}_{model_tag}.json","w") as f:
                json.dump(summary, f, indent=2)

            records.append(summary)

            print(
                f"[K={K:3},W={W:2},γ={GAM}] {run_tag}  "
                f"AUC_edg={pv_auc['edgington']:.3f}  "
                f"TPR01_edg={pv_tpr['edgington']*100:.2f}%   "
                f"AUC_log={auc_log:.3f}  "
                f"TPR01_log={tpr_log*100:.2f}%"
            )

        # aggregate
        df = pd.DataFrame(records)
        agg = {col: {"mean":float(df[col].mean()), "std":float(df[col].std())}
               for col in df.columns if col.startswith(("auc_","tpr01_"))}
        with open(f"{exp_dir}/aggregate.json","w") as f:
            json.dump(agg, f, indent=2)

        # update best_metric (use W for Edgington, γ for logistic)
        for metric,(mean,_,_) in zip(agg.keys(), [(agg[c]["mean"],None,None) for c in agg]):
            is_log = metric in ("auc_log","tpr01_log")
            param  = GAM if is_log else W
            if metric not in best_metric or agg[metric]["mean"] > best_metric[metric][0]:
                best_metric[metric] = (agg[metric]["mean"], K, param)

# ──────────────────────── leaderboard ────────────────────────────────────────
print("\n=========  BEST COMBINATION PER METRIC (mean over 10 runs)  =========")
for metric,(score,K,param) in sorted(best_metric.items()):
    label = "γ" if metric in ("auc_log","tpr01_log") else "W"
    print(f"{metric:<12}  {score:7.3f}   (K={K}, {label}={param})")
print("=====================================================================")

# write-out JSON
with open(f"{OUT_PARENT}/{domain_name}_{model_tag}/grid_best.json","w") as f:
    json.dump({
        metric: {
            "score": score,
            "K":      K,
            "weight": None if metric in ("auc_log","tpr01_log") else param,
            "gamma":  None if metric not in ("auc_log","tpr01_log") else param
        }
        for metric,(score,K,param) in best_metric.items()
    }, f, indent=2)
print(f"✓ wrote overall leaderboard → {OUT_PARENT}/{domain_name}_{model_tag}/grid_best.json")

◆ Extracting CAMIA signals once (K=0)…

Signal-extraction: 100%|██████████| 323/323 [06:30<00:00,  1.21s/it]
Signal-extraction: 100%|██████████| 323/323 [06:19<00:00,  1.17s/it]

◆   done  –  646 mem + 646 non-mem passages
◇ now evaluating  K=0   W=0   γ=1.0
[K=  0,W= 0,γ=1.0] run_00  AUC_edg=0.580  TPR01_edg=1.77%   AUC_log=0.573  TPR01_log=4.42%
[K=  0,W= 0,γ=1.0] run_01  AUC_edg=0.580  TPR01_edg=1.99%   AUC_log=0.548  TPR01_log=3.31%
[K=  0,W= 0,γ=1.0] run_02  AUC_edg=0.579  TPR01_edg=2.87%   AUC_log=0.565  TPR01_log=4.19%
[K=  0,W= 0,γ=1.0] run_03  AUC_edg=0.588  TPR01_edg=2.87%   AUC_log=0.515  TPR01_log=3.09%
[K=  0,W= 0,γ=1.0] run_04  AUC_edg=0.601  TPR01_edg=2.65%   AUC_log=0.516  TPR01_log=1.10%
[K=  0,W= 0,γ=1.0] run_05  AUC_edg=0.563  TPR01_edg=1.32%   AUC_log=0.552  TPR01_log=0.66%
[K=  0,W= 0,γ=1.0] run_06  AUC_edg=0.561  TPR01_edg=2.43%   AUC_log=0.590  TPR01_log=3.31%
[K=  0,W= 0,γ=1.0] run_07  AUC_edg=0.577  TPR01_edg=1.55%   AUC_log=0.534  TPR01_log=1.55%
[K=  0,W= 0,γ=1.0] run_08  AUC_edg=0.581  TPR01_edg=5.96%   AUC_log=0.583  TPR01_log=3.53%
[K=  0,W= 0,γ=1.0] run_09  AUC_edg=0.564  TPR01_edg=2.43%   AUC_log=0.540  TPR01_log=1.55%
◇ now evaluating  K=25   W=9   γ=1
[K= 25,W= 9,γ=1] run_00  AUC_edg=0.580  TPR01_edg=3.75%   AUC_log=0.571  TPR01_log=2.87%
[K= 25,W= 9,γ=1] run_01  AUC_edg=0.579  TPR01_edg=3.31%   AUC_log=0.549  TPR01_log=3.53%
[K= 25,W= 9,γ=1] run_02  AUC_edg=0.577  TPR01_edg=3.97%   AUC_log=0.569  TPR01_log=3.53%
[K= 25,W= 9,γ=1] run_03  AUC_edg=0.587  TPR01_edg=3.97%   AUC_log=0.516  TPR01_log=2.87%
[K= 25,W= 9,γ=1] run_04  AUC_edg=0.601  TPR01_edg=4.64%   AUC_log=0.529  TPR01_log=1.32%
[K= 25,W= 9,γ=1] run_05  AUC_edg=0.561  TPR01_edg=3.75%   AUC_log=0.551  TPR01_log=0.88%
[K= 25,W= 9,γ=1] run_06  AUC_edg=0.559  TPR01_edg=4.19%   AUC_log=0.589  TPR01_log=2.21%
[K= 25,W= 9,γ=1] run_07  AUC_edg=0.577  TPR01_edg=2.43%   AUC_log=0.536  TPR01_log=1.77%
[K= 25,W= 9,γ=1] run_08  AUC_edg=0.579  TPR01_edg=4.86%   AUC_log=0.578  TPR01_log=3.97%
[K= 25,W= 9,γ=1] run_09  AUC_edg=0.562  TPR01_edg=3.75%   AUC_log=0.541  TPR01_log=1.55%
◇ now evaluating  K=25   W=18   γ=2
[K= 25,W=18,γ=2] run_00  AUC_edg=0.578  TPR01_edg=3.75%   AUC_log=0.570  TPR01_log=2.87%
[K= 25,W=18,γ=2] run_01  AUC_edg=0.577  TPR01_edg=3.31%   AUC_log=0.549  TPR01_log=3.53%
[K= 25,W=18,γ=2] run_02  AUC_edg=0.573  TPR01_edg=4.42%   AUC_log=0.569  TPR01_log=3.53%
[K= 25,W=18,γ=2] run_03  AUC_edg=0.583  TPR01_edg=3.31%   AUC_log=0.516  TPR01_log=2.87%
[K= 25,W=18,γ=2] run_04  AUC_edg=0.599  TPR01_edg=4.86%   AUC_log=0.529  TPR01_log=1.32%
[K= 25,W=18,γ=2] run_05  AUC_edg=0.558  TPR01_edg=4.64%   AUC_log=0.551  TPR01_log=0.88%
[K= 25,W=18,γ=2] run_06  AUC_edg=0.555  TPR01_edg=4.19%   AUC_log=0.589  TPR01_log=2.21%
[K= 25,W=18,γ=2] run_07  AUC_edg=0.574  TPR01_edg=2.43%   AUC_log=0.536  TPR01_log=1.77%
[K= 25,W=18,γ=2] run_08  AUC_edg=0.577  TPR01_edg=4.64%   AUC_log=0.578  TPR01_log=3.97%
[K= 25,W=18,γ=2] run_09  AUC_edg=0.560  TPR01_edg=3.75%   AUC_log=0.541  TPR01_log=1.55%
◇ now evaluating  K=25   W=36   γ=3
[K= 25,W=36,γ=3] run_00  AUC_edg=0.572  TPR01_edg=2.87%   AUC_log=0.571  TPR01_log=2.87%
[K= 25,W=36,γ=3] run_01  AUC_edg=0.571  TPR01_edg=2.87%   AUC_log=0.549  TPR01_log=3.53%
[K= 25,W=36,γ=3] run_02  AUC_edg=0.567  TPR01_edg=3.75%   AUC_log=0.569  TPR01_log=3.53%
[K= 25,W=36,γ=3] run_03  AUC_edg=0.575  TPR01_edg=3.53%   AUC_log=0.516  TPR01_log=2.87%
[K= 25,W=36,γ=3] run_04  AUC_edg=0.592  TPR01_edg=4.42%   AUC_log=0.529  TPR01_log=1.32%
[K= 25,W=36,γ=3] run_05  AUC_edg=0.553  TPR01_edg=3.75%   AUC_log=0.551  TPR01_log=0.88%
[K= 25,W=36,γ=3] run_06  AUC_edg=0.549  TPR01_edg=3.53%   AUC_log=0.589  TPR01_log=2.21%
[K= 25,W=36,γ=3] run_07  AUC_edg=0.568  TPR01_edg=3.09%   AUC_log=0.536  TPR01_log=1.77%
[K= 25,W=36,γ=3] run_08  AUC_edg=0.570  TPR01_edg=3.97%   AUC_log=0.578  TPR01_log=3.97%
[K= 25,W=36,γ=3] run_09  AUC_edg=0.554  TPR01_edg=3.09%   AUC_log=0.541  TPR01_log=1.55%
◇ now evaluating  K=25   W=72   γ=4
[K= 25,W=72,γ=4] run_00  AUC_edg=0.560  TPR01_edg=2.65%   AUC_log=0.571  TPR01_log=2.87%
[K= 25,W=72,γ=4] run_01  AUC_edg=0.559  TPR01_edg=2.21%   AUC_log=0.549  TPR01_log=3.53%
[K= 25,W=72,γ=4] run_02  AUC_edg=0.554  TPR01_edg=3.09%   AUC_log=0.569  TPR01_log=3.53%
[K= 25,W=72,γ=4] run_03  AUC_edg=0.562  TPR01_edg=3.09%   AUC_log=0.516  TPR01_log=2.87%
[K= 25,W=72,γ=4] run_04  AUC_edg=0.577  TPR01_edg=3.75%   AUC_log=0.529  TPR01_log=1.32%
[K= 25,W=72,γ=4] run_05  AUC_edg=0.544  TPR01_edg=3.09%   AUC_log=0.551  TPR01_log=0.88%
[K= 25,W=72,γ=4] run_06  AUC_edg=0.539  TPR01_edg=2.65%   AUC_log=0.589  TPR01_log=2.21%
[K= 25,W=72,γ=4] run_07  AUC_edg=0.556  TPR01_edg=1.99%   AUC_log=0.536  TPR01_log=1.77%
[K= 25,W=72,γ=4] run_08  AUC_edg=0.558  TPR01_edg=3.09%   AUC_log=0.578  TPR01_log=3.97%
[K= 25,W=72,γ=4] run_09  AUC_edg=0.546  TPR01_edg=2.21%   AUC_log=0.541  TPR01_log=1.55%
◇ now evaluating  K=100   W=9   γ=1
[K=100,W= 9,γ=1] run_00  AUC_edg=0.580  TPR01_edg=3.97%   AUC_log=0.530  TPR01_log=1.55%
[K=100,W= 9,γ=1] run_01  AUC_edg=0.579  TPR01_edg=3.31%   AUC_log=0.548  TPR01_log=3.53%
[K=100,W= 9,γ=1] run_02  AUC_edg=0.577  TPR01_edg=3.97%   AUC_log=0.568  TPR01_log=3.97%
[K=100,W= 9,γ=1] run_03  AUC_edg=0.586  TPR01_edg=3.97%   AUC_log=0.520  TPR01_log=2.65%
[K=100,W= 9,γ=1] run_04  AUC_edg=0.601  TPR01_edg=4.64%   AUC_log=0.501  TPR01_log=0.66%
[K=100,W= 9,γ=1] run_05  AUC_edg=0.560  TPR01_edg=3.75%   AUC_log=0.555  TPR01_log=0.66%
[K=100,W= 9,γ=1] run_06  AUC_edg=0.559  TPR01_edg=3.97%   AUC_log=0.589  TPR01_log=3.09%
[K=100,W= 9,γ=1] run_07  AUC_edg=0.577  TPR01_edg=2.43%   AUC_log=0.536  TPR01_log=1.77%
[K=100,W= 9,γ=1] run_08  AUC_edg=0.579  TPR01_edg=4.86%   AUC_log=0.567  TPR01_log=3.97%
[K=100,W= 9,γ=1] run_09  AUC_edg=0.562  TPR01_edg=3.75%   AUC_log=0.541  TPR01_log=1.55%
◇ now evaluating  K=100   W=18   γ=2
[K=100,W=18,γ=2] run_00  AUC_edg=0.578  TPR01_edg=3.75%   AUC_log=0.529  TPR01_log=1.55%
[K=100,W=18,γ=2] run_01  AUC_edg=0.577  TPR01_edg=3.31%   AUC_log=0.548  TPR01_log=3.53%
[K=100,W=18,γ=2] run_02  AUC_edg=0.573  TPR01_edg=4.19%   AUC_log=0.568  TPR01_log=3.97%
[K=100,W=18,γ=2] run_03  AUC_edg=0.582  TPR01_edg=3.31%   AUC_log=0.520  TPR01_log=2.65%
[K=100,W=18,γ=2] run_04  AUC_edg=0.599  TPR01_edg=4.86%   AUC_log=0.501  TPR01_log=0.66%
[K=100,W=18,γ=2] run_05  AUC_edg=0.557  TPR01_edg=4.42%   AUC_log=0.555  TPR01_log=0.66%
[K=100,W=18,γ=2] run_06  AUC_edg=0.555  TPR01_edg=4.19%   AUC_log=0.589  TPR01_log=3.31%
[K=100,W=18,γ=2] run_07  AUC_edg=0.574  TPR01_edg=3.09%   AUC_log=0.536  TPR01_log=1.77%
[K=100,W=18,γ=2] run_08  AUC_edg=0.576  TPR01_edg=4.64%   AUC_log=0.567  TPR01_log=3.97%
[K=100,W=18,γ=2] run_09  AUC_edg=0.559  TPR01_edg=3.75%   AUC_log=0.541  TPR01_log=1.55%
◇ now evaluating  K=100   W=36   γ=3
[K=100,W=36,γ=3] run_00  AUC_edg=0.572  TPR01_edg=2.87%   AUC_log=0.529  TPR01_log=1.55%
[K=100,W=36,γ=3] run_01  AUC_edg=0.571  TPR01_edg=2.87%   AUC_log=0.548  TPR01_log=3.53%
[K=100,W=36,γ=3] run_02  AUC_edg=0.566  TPR01_edg=3.75%   AUC_log=0.568  TPR01_log=3.97%
[K=100,W=36,γ=3] run_03  AUC_edg=0.575  TPR01_edg=3.53%   AUC_log=0.520  TPR01_log=2.65%
[K=100,W=36,γ=3] run_04  AUC_edg=0.592  TPR01_edg=5.08%   AUC_log=0.501  TPR01_log=0.66%
[K=100,W=36,γ=3] run_05  AUC_edg=0.552  TPR01_edg=3.75%   AUC_log=0.555  TPR01_log=0.66%
[K=100,W=36,γ=3] run_06  AUC_edg=0.549  TPR01_edg=3.53%   AUC_log=0.589  TPR01_log=3.09%
[K=100,W=36,γ=3] run_07  AUC_edg=0.568  TPR01_edg=3.09%   AUC_log=0.536  TPR01_log=1.77%
[K=100,W=36,γ=3] run_08  AUC_edg=0.570  TPR01_edg=3.97%   AUC_log=0.566  TPR01_log=3.97%
[K=100,W=36,γ=3] run_09  AUC_edg=0.554  TPR01_edg=2.87%   AUC_log=0.541  TPR01_log=1.55%
◇ now evaluating  K=100   W=72   γ=4
[K=100,W=72,γ=4] run_00  AUC_edg=0.560  TPR01_edg=2.65%   AUC_log=0.529  TPR01_log=1.55%
[K=100,W=72,γ=4] run_01  AUC_edg=0.559  TPR01_edg=2.21%   AUC_log=0.548  TPR01_log=3.53%
[K=100,W=72,γ=4] run_02  AUC_edg=0.554  TPR01_edg=3.09%   AUC_log=0.568  TPR01_log=3.97%
[K=100,W=72,γ=4] run_03  AUC_edg=0.562  TPR01_edg=2.65%   AUC_log=0.520  TPR01_log=2.65%
[K=100,W=72,γ=4] run_04  AUC_edg=0.578  TPR01_edg=3.97%   AUC_log=0.501  TPR01_log=0.66%
[K=100,W=72,γ=4] run_05  AUC_edg=0.543  TPR01_edg=3.09%   AUC_log=0.555  TPR01_log=0.66%
[K=100,W=72,γ=4] run_06  AUC_edg=0.540  TPR01_edg=2.87%   AUC_log=0.589  TPR01_log=3.09%
[K=100,W=72,γ=4] run_07  AUC_edg=0.556  TPR01_edg=1.77%   AUC_log=0.536  TPR01_log=1.77%
[K=100,W=72,γ=4] run_08  AUC_edg=0.558  TPR01_edg=3.09%   AUC_log=0.566  TPR01_log=3.97%
[K=100,W=72,γ=4] run_09  AUC_edg=0.545  TPR01_edg=2.65%   AUC_log=0.541  TPR01_log=1.55%

=========  BEST COMBINATION PER METRIC (mean over 10 runs)  =========
auc_edgington    0.577   (K=0, W=0)
auc_fisher      0.435   (K=100, W=72)
auc_george      0.577   (K=0, W=0)
auc_log         0.553   (K=25, γ=3)
auc_pearson     0.568   (K=0, W=0)
tpr01_edgington    0.040   (K=100, W=18)
tpr01_fisher    0.006   (K=25, W=72)
tpr01_george    0.057   (K=0, W=0)
tpr01_log       0.027   (K=0, γ=1.0)
tpr01_pearson    0.025   (K=100, W=36)
=====================================================================
✓ wrote overall leaderboard → experiment_whiten/hackernews_pythia70m-dedup/grid_best.json

In [ ]:
###############################################################################
# OLD Cell 6 – Grid-search driver: CAMIA  +  Neighbourhood Comparison            #
###############################################################################
import os, json, pandas as pd, numpy as np, itertools, time
from sklearn.metrics import roc_auc_score, roc_curve
from accelerate import Accelerator

# ------------------------ experiment grid ------------------------------------
GRID_NEI_K      = [0, 25, 100]          # 1× “vanilla CAMIA”  +  2× with neighbours
GRID_NEI_WEIGHT = [9, 18, 36, 72]       # ⧺ (ignored when K == 0)
GRID_NEI_GAMMA  = [1, 2, 3, 4]
N_RUNS          = 10                    # per (K,W) point
OUT_PARENT      = "experiment"

# ------------------------ static model / data conf ---------------------------
domain_name  = "github"
split_name   = "ngram_7_0.2"
num_samples  = 1000
suite,size,dedup = "Pythia","70M",True
model_tag    = f"{suite}{size}{'-dedup' if dedup else ''}".lower()

my_hf_token  = "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"
ds           = load_dataset("iamgroot42/mimir", domain_name,
                            split=split_name, token=my_hf_token)
num_samples  = min(num_samples, len(ds["member"]))
all_members  = ds["member"][:num_samples]
all_nonmem   = ds["nonmember"][:num_samples]

model_name   = get_model_name(suite,size,dedup)
tokenizer    = AutoTokenizer.from_pretrained(model_name); tokenizer.add_special_tokens({'pad_token':'[PAD]'})
acc          = Accelerator()
model        = AutoModelForCausalLM.from_pretrained(
                  model_name, torch_dtype=torch.float16, low_cpu_mem_usage=True)
model        = acc.prepare(model).eval()

# ───────────────────────── helpers ───────────────────────────────────────────
def _auc_tpr01(pos, neg):
    y = [1]*len(pos) + [0]*len(neg)
    s = -np.concatenate([pos, neg])
    fpr, tpr, _ = roc_curve(y, s)
    return roc_auc_score(y, s), tpr[np.argmin(np.abs(fpr-0.01))]

def gather_all_signals(nei_k):
    """Compute the 72-signal dicts *once* for the given NEI_K."""
    C.NEI_K = nei_k
    return (
        gather_signals_for_dataset(all_members,  model, tokenizer, tag="member",   batch_size=2),
        gather_signals_for_dataset(all_nonmem,   model, tokenizer, tag="nonmember",batch_size=2)
    )

# outer scoreboard
best_metric = {}   # metric_name → (score, K, W)

# ─────────────────── NEW: one-off extraction without neighbours ───────────────
print("◆ Extracting CAMIA signals once (K=0) …")
C.NEI_K = 0                                  # <-- ensure no neighbours
base_mem = gather_signals_for_dataset(all_members,  model, tokenizer,
                                      tag="member",   batch_size=2)
base_non = gather_signals_for_dataset(all_nonmem,   model, tokenizer,
                                      tag="nonmember",batch_size=2)
print("◆   done  –  {} + {} passages".format(len(base_mem), len(base_non)))

# ───────────────────────── grid loop ─────────────────────────────────────────
for K in GRID_NEI_K:
    C.NEI_K = K
    
    # ---------- build per-K feature dicts quickly --------------------
    mem_sdicts = add_nei_delta(
        base_mem,
        _load_cached_neighbours(domain_name, split_name, "member"),
        K,
        model,
        tokenizer
    )
    non_sdicts = add_nei_delta(
        base_non,
        _load_cached_neighbours(domain_name, split_name, "nonmember"),
        K,
        model,
        tokenizer
    )

    # choose which W values to evaluate
    #W_list = [0] if K == 0 else GRID_NEI_WEIGHT

    for W, GAM in zip(GRID_NEI_WEIGHT if K else[0],
                      GRID_NEI_GAMMA if K else [1.0]):
        C.NEI_WEIGHT = W
        NEI_GAMMA = GAM

        print(f"◇ now evaluating K={K}   W={W}   γ={GAM}")

        exp_dir = f"{OUT_PARENT}/{domain_name}_{model_tag}/K{K}_W{W}"
        os.makedirs(exp_dir, exist_ok=True)

        # --------------- 10× runs ------------------------------------------
        records = []
        for run in range(N_RUNS):
            run_tag   = f"run_{run:02d}"
            run_dir   = f"{exp_dir}/{run_tag}"
            os.makedirs(run_dir, exist_ok=True)

            rng       = np.random.default_rng(42+run)
            idx_mem   = rng.permutation(num_samples)
            idx_non   = rng.permutation(num_samples)
            cut       = int(num_samples*0.30)
            mem_cal_i, mem_test_i  = idx_mem[:cut], idx_mem[cut:]
            non_cal_i, non_test_i  = idx_non[:cut], idx_non[cut:]

            mem_cal_sd  = [mem_sdicts [i] for i in mem_cal_i]
            non_cal_sd  = [non_sdicts [i] for i in non_cal_i]
            mem_test_sd = [mem_sdicts [i] for i in mem_test_i]
            non_test_sd = [non_sdicts [i] for i in non_test_i]

            ref_dict  = edgington_fit(non_cal_sd)

            pv_auc, pv_tpr = {}, {}
            for m in ["fisher","pearson","george","edgington"]:
                mem_s = pv_score_batch(mem_test_sd,  ref_dict, m)
                non_s = pv_score_batch(non_test_sd,  ref_dict, m)
                pv_auc[m], pv_tpr[m] = _auc_tpr01(mem_s, non_s)

            clf, meta   = logistic_fit(mem_cal_sd, non_cal_sd)
            mem_s_log   = logistic_score_batch(mem_test_sd, clf, meta)
            non_s_log   = logistic_score_batch(non_test_sd, clf, meta)
            auc_log, tpr_log = _auc_tpr01(mem_s_log, non_s_log)

            # ---------- per-run CSV with *all* signals --------------------
            rows=[]
            for j,i in enumerate(mem_test_i):
                r = {"text_index":int(i),"membership_label":1,"set_split":"test"}
                r.update(mem_test_sd[j])
                rows.append(r)
            for j,i in enumerate(non_test_i):
                r = {"text_index":int(i),"membership_label":0,"set_split":"test"}
                r.update(non_test_sd[j])
                rows.append(r)
            pd.DataFrame(rows).to_csv(f"{run_dir}/results_{domain_name}_{model_tag}.csv",
                                      index=False)

            # per-run json summary
            summary = {"model_tag":model_tag, "domain":domain_name,
                       "nei_K":K, "nei_weight":W,
                       **{f"auc_{m}":float(pv_auc[m])   for m in pv_auc},
                       **{f"tpr01_{m}":float(pv_tpr[m]) for m in pv_tpr},
                       "nei_gamma": GAM,
                       "auc_log":float(auc_log), "tpr01_log":float(tpr_log)}
            json.dump(summary, open(f"{run_dir}/summary_{domain_name}_{model_tag}.json","w"), indent=2)

            records.append(summary)   # keep for aggregate

            # ------------------------------------------------------------------
            # ADD just before the big print-line inside the inner-run loop
            # ------------------------------------------------------------------
            if K > 0:                                     # K=0 → no neighbour feature
                mem_nd  = [d["nei_delta"] for d in mem_test_sd  if "nei_delta" in d]
                non_nd  = [d["nei_delta"] for d in non_test_sd  if "nei_delta" in d]
                mem_mu  = float(np.mean(mem_nd)) if mem_nd else float("nan")
                non_mu  = float(np.mean(non_nd)) if non_nd else float("nan")
            else:                                          # keep the variables defined
                mem_mu  = non_mu = float("nan")
            # ------------------------------------------------------------------

            
            print(f"[K={K:3},W={W:2}] {run_tag}  "
                  f"AUC_edg={pv_auc['edgington']:.3f}  "
                  f"TPR01_edg={pv_tpr['edgington']*100:.2f}%")

        # --------------- aggregate.json -----------------------------------
        df = pd.DataFrame(records)
        agg = {col: {"mean":float(df[col].mean()), "std":float(df[col].std())}
               for col in df.columns if col.startswith(("auc_","tpr01_"))}
        json.dump(agg, open(f"{exp_dir}/aggregate.json","w"), indent=2)

        # ------- update global best-of-grid tracker -----------------------
        for metric,val in agg.items():
            mean = val["mean"]
            if metric not in best_metric or mean > best_metric[metric][0]:
                best_metric[metric] = (mean, K, W)

# ──────────────────────── grid leaderboard ───────────────────────────────────
print("\n=========  BEST COMBINATION PER METRIC (mean over 10 runs)  =========")
for k,(score,K,W) in sorted(best_metric.items()):
    print(f"{k:<12}  {score:7.3f}   (K={K}, W={W})")
print("=====================================================================")

# --------------- OPTIONAL: store full leaderboard --------------------------
with open(f"{OUT_PARENT}/{domain_name}_{model_tag}/grid_best.json","w") as f:
    json.dump({k: {"score":s, "K":K, "W":W, "gamma": 1.0 if W==0           
                      else GRID_NEI_GAMMA[GRID_NEI_WEIGHT.index(W)]} for k,(s,K,W) in best_metric.items()},
              f, indent=2)
print(f"✓ wrote overall leaderboard → "
      f"{OUT_PARENT}/{domain_name}_{model_tag}/grid_best.json")

◆ Extracting CAMIA signals once (K=0) …

Signal-extraction: 100%|██████████| 134/134 [02:45<00:00,  1.24s/it]
Signal-extraction: 100%|██████████| 134/134 [02:46<00:00,  1.24s/it]

◆   done  –  268 + 268 passages
◇ now evaluating K=0   W=0   γ=1.0
[K=  0,W= 0] run_00  AUC_edg=0.845  TPR01_edg=50.53%
[K=  0,W= 0] run_01  AUC_edg=0.852  TPR01_edg=36.17%
[K=  0,W= 0] run_02  AUC_edg=0.843  TPR01_edg=42.02%
[K=  0,W= 0] run_03  AUC_edg=0.851  TPR01_edg=29.79%
[K=  0,W= 0] run_04  AUC_edg=0.850  TPR01_edg=39.36%
[K=  0,W= 0] run_05  AUC_edg=0.856  TPR01_edg=48.94%
[K=  0,W= 0] run_06  AUC_edg=0.869  TPR01_edg=48.94%
[K=  0,W= 0] run_07  AUC_edg=0.858  TPR01_edg=50.00%
[K=  0,W= 0] run_08  AUC_edg=0.866  TPR01_edg=49.47%
[K=  0,W= 0] run_09  AUC_edg=0.828  TPR01_edg=46.81%
◇ now evaluating K=25   W=9   γ=1
[K= 25,W= 9] run_00  AUC_edg=0.848  TPR01_edg=55.85%
[K= 25,W= 9] run_01  AUC_edg=0.861  TPR01_edg=46.28%
[K= 25,W= 9] run_02  AUC_edg=0.844  TPR01_edg=47.87%
[K= 25,W= 9] run_03  AUC_edg=0.854  TPR01_edg=53.19%
[K= 25,W= 9] run_04  AUC_edg=0.858  TPR01_edg=54.26%
[K= 25,W= 9] run_05  AUC_edg=0.861  TPR01_edg=54.79%
[K= 25,W= 9] run_06  AUC_edg=0.876  TPR01_edg=50.00%
[K= 25,W= 9] run_07  AUC_edg=0.861  TPR01_edg=48.94%
[K= 25,W= 9] run_08  AUC_edg=0.870  TPR01_edg=51.06%
[K= 25,W= 9] run_09  AUC_edg=0.836  TPR01_edg=43.09%
◇ now evaluating K=25   W=18   γ=2
[K= 25,W=18] run_00  AUC_edg=0.846  TPR01_edg=52.66%
[K= 25,W=18] run_01  AUC_edg=0.863  TPR01_edg=45.21%
[K= 25,W=18] run_02  AUC_edg=0.843  TPR01_edg=46.81%
[K= 25,W=18] run_03  AUC_edg=0.853  TPR01_edg=51.06%
[K= 25,W=18] run_04  AUC_edg=0.857  TPR01_edg=51.06%
[K= 25,W=18] run_05  AUC_edg=0.860  TPR01_edg=57.45%
[K= 25,W=18] run_06  AUC_edg=0.875  TPR01_edg=49.47%
[K= 25,W=18] run_07  AUC_edg=0.860  TPR01_edg=48.40%
[K= 25,W=18] run_08  AUC_edg=0.868  TPR01_edg=49.47%
[K= 25,W=18] run_09  AUC_edg=0.840  TPR01_edg=42.55%
◇ now evaluating K=25   W=36   γ=3
[K= 25,W=36] run_00  AUC_edg=0.842  TPR01_edg=53.72%
[K= 25,W=36] run_01  AUC_edg=0.857  TPR01_edg=46.28%
[K= 25,W=36] run_02  AUC_edg=0.835  TPR01_edg=45.74%
[K= 25,W=36] run_03  AUC_edg=0.844  TPR01_edg=48.94%
[K= 25,W=36] run_04  AUC_edg=0.853  TPR01_edg=50.53%
[K= 25,W=36] run_05  AUC_edg=0.853  TPR01_edg=52.13%
[K= 25,W=36] run_06  AUC_edg=0.870  TPR01_edg=48.94%
[K= 25,W=36] run_07  AUC_edg=0.853  TPR01_edg=47.34%
[K= 25,W=36] run_08  AUC_edg=0.862  TPR01_edg=46.81%
[K= 25,W=36] run_09  AUC_edg=0.839  TPR01_edg=43.09%
◇ now evaluating K=25   W=72   γ=4
[K= 25,W=72] run_00  AUC_edg=0.834  TPR01_edg=50.53%
[K= 25,W=72] run_01  AUC_edg=0.851  TPR01_edg=47.34%
[K= 25,W=72] run_02  AUC_edg=0.824  TPR01_edg=46.28%
[K= 25,W=72] run_03  AUC_edg=0.833  TPR01_edg=47.87%
[K= 25,W=72] run_04  AUC_edg=0.844  TPR01_edg=42.55%
[K= 25,W=72] run_05  AUC_edg=0.843  TPR01_edg=47.87%
[K= 25,W=72] run_06  AUC_edg=0.860  TPR01_edg=50.53%
[K= 25,W=72] run_07  AUC_edg=0.843  TPR01_edg=46.81%
[K= 25,W=72] run_08  AUC_edg=0.852  TPR01_edg=45.21%
[K= 25,W=72] run_09  AUC_edg=0.835  TPR01_edg=42.55%
◇ now evaluating K=100   W=9   γ=1
[K=100,W= 9] run_00  AUC_edg=0.847  TPR01_edg=55.85%
[K=100,W= 9] run_01  AUC_edg=0.861  TPR01_edg=46.81%
[K=100,W= 9] run_02  AUC_edg=0.845  TPR01_edg=47.87%
[K=100,W= 9] run_03  AUC_edg=0.855  TPR01_edg=53.19%
[K=100,W= 9] run_04  AUC_edg=0.858  TPR01_edg=54.26%
[K=100,W= 9] run_05  AUC_edg=0.861  TPR01_edg=54.79%
[K=100,W= 9] run_06  AUC_edg=0.877  TPR01_edg=50.00%
[K=100,W= 9] run_07  AUC_edg=0.862  TPR01_edg=48.94%
[K=100,W= 9] run_08  AUC_edg=0.870  TPR01_edg=51.06%
[K=100,W= 9] run_09  AUC_edg=0.837  TPR01_edg=43.62%
◇ now evaluating K=100   W=18   γ=2
[K=100,W=18] run_00  AUC_edg=0.846  TPR01_edg=52.66%
[K=100,W=18] run_01  AUC_edg=0.862  TPR01_edg=44.68%
[K=100,W=18] run_02  AUC_edg=0.842  TPR01_edg=46.81%
[K=100,W=18] run_03  AUC_edg=0.853  TPR01_edg=51.06%
[K=100,W=18] run_04  AUC_edg=0.858  TPR01_edg=51.06%
[K=100,W=18] run_05  AUC_edg=0.860  TPR01_edg=57.45%
[K=100,W=18] run_06  AUC_edg=0.875  TPR01_edg=49.47%
[K=100,W=18] run_07  AUC_edg=0.860  TPR01_edg=48.40%
[K=100,W=18] run_08  AUC_edg=0.869  TPR01_edg=49.47%
[K=100,W=18] run_09  AUC_edg=0.840  TPR01_edg=42.55%
◇ now evaluating K=100   W=36   γ=3
[K=100,W=36] run_00  AUC_edg=0.842  TPR01_edg=51.60%
[K=100,W=36] run_01  AUC_edg=0.858  TPR01_edg=46.28%
[K=100,W=36] run_02  AUC_edg=0.835  TPR01_edg=46.28%
[K=100,W=36] run_03  AUC_edg=0.844  TPR01_edg=48.94%
[K=100,W=36] run_04  AUC_edg=0.854  TPR01_edg=50.53%
[K=100,W=36] run_05  AUC_edg=0.854  TPR01_edg=53.72%
[K=100,W=36] run_06  AUC_edg=0.870  TPR01_edg=48.94%
[K=100,W=36] run_07  AUC_edg=0.853  TPR01_edg=47.34%
[K=100,W=36] run_08  AUC_edg=0.862  TPR01_edg=46.81%
[K=100,W=36] run_09  AUC_edg=0.839  TPR01_edg=43.09%
◇ now evaluating K=100   W=72   γ=4
[K=100,W=72] run_00  AUC_edg=0.835  TPR01_edg=51.60%
[K=100,W=72] run_01  AUC_edg=0.851  TPR01_edg=47.34%
[K=100,W=72] run_02  AUC_edg=0.824  TPR01_edg=47.34%
[K=100,W=72] run_03  AUC_edg=0.833  TPR01_edg=47.87%
[K=100,W=72] run_04  AUC_edg=0.844  TPR01_edg=42.55%
[K=100,W=72] run_05  AUC_edg=0.844  TPR01_edg=47.87%
[K=100,W=72] run_06  AUC_edg=0.860  TPR01_edg=50.53%
[K=100,W=72] run_07  AUC_edg=0.844  TPR01_edg=46.81%
[K=100,W=72] run_08  AUC_edg=0.852  TPR01_edg=45.21%
[K=100,W=72] run_09  AUC_edg=0.835  TPR01_edg=42.55%

=========  BEST COMBINATION PER METRIC (mean over 10 runs)  =========
auc_edgington    0.857   (K=100, W=9)
auc_fisher      0.166   (K=25, W=72)
auc_george      0.855   (K=0, W=0)
auc_log         0.860   (K=0, W=0)
auc_pearson     0.859   (K=100, W=9)
tpr01_edgington    0.506   (K=100, W=9)
tpr01_fisher    0.001   (K=25, W=9)
tpr01_george    0.485   (K=100, W=18)
tpr01_log       0.515   (K=0, W=0)
tpr01_pearson    0.434   (K=100, W=72)
=====================================================================
✓ wrote overall leaderboard → experiment/github_pythia70m-dedup/grid_best.json

In [ ]:
###############################################################################
# Cell 7 – Diagnostics for *one* saved run  (new folder layout)               #
###############################################################################
import os, json, ast, numpy as np, pandas as pd, matplotlib.pyplot as plt
from collections import defaultdict
from sklearn.metrics import roc_auc_score, roc_curve

# --------------------------------------------------------------------------- #
# -------- pick WHAT you want to inspect ------------------------------------ #
RUN_DOMAIN     = "arxiv"      # ← one of your domains
RUN_MODEL_TAG  = "pythia70m-dedup"     # exactly as in Cell-6
RUN_K          = 0                    # neighbour count  (0 / 25 / 100 …)
RUN_W          = 0                    # neighbour weight (0 for K=0)
RUN_ID         = "run_00"              # run_00 … run_09
# --------------------------------------------------------------------------- #

RUN_DIR = (f"10x_results_highloss_k_nei/{RUN_DOMAIN}_{RUN_MODEL_TAG}/"
           f"K{RUN_K}_W{RUN_W}/{RUN_ID}")

csv_path  = f"{RUN_DIR}/results_{RUN_DOMAIN}_{RUN_MODEL_TAG}.csv"
json_path = f"{RUN_DIR}/summary_{RUN_DOMAIN}_{RUN_MODEL_TAG}.json"

if not os.path.exists(csv_path):
    raise FileNotFoundError(csv_path)

df   = pd.read_csv(csv_path)
meta = json.load(open(json_path))

# ----------- basic splits --------------------------------------------------- #
df_test = df[df.set_split == "test"]            # ← new column name
df_mem  = df_test[df_test.membership_label == 1]
df_non  = df_test[df_test.membership_label == 0]

def tpr01(pos, neg):
    y   = [1]*len(pos) + [0]*len(neg)
    s   = -np.concatenate([pos, neg])
    fpr, tpr, _ = roc_curve(y, s)
    return tpr[np.argmin(np.abs(fpr-0.01))] * 100

# ----------- 1) histograms for every scalar feature ------------------------- #
skip = {"text_index", "membership_label", "set_split",
        "edgington_score", "logistic_score", "bestpv_score",
        "loss_seq_orig", "nei_texts"}

for feat in [c for c in df_test.columns if c not in skip]:
    plt.figure(figsize=(4,2))
    plt.hist(df_mem[feat], 40, alpha=.5, label="mem")
    plt.hist(df_non[feat], 40, alpha=.5, label="non")
    plt.title(f"{feat}  • TPR@1% = {tpr01(df_mem[feat], df_non[feat]):.1f}%")
    plt.legend(); plt.tight_layout(); plt.show()

# ----------- 2) token-loss curves (first / last 100) ------------------------ #
if "loss_seq_orig" in df_test.columns:
    def _avg_curve(dfs, first=True, K=100):
        seqs = [ast.literal_eval(s) if isinstance(s,str) else s
                for s in dfs.loss_seq_orig]
        arr  = np.full((len(seqs), K), np.nan)
        for i,s in enumerate(seqs):
            seg = s[:K] if first else s[-K:]
            if first:   arr[i,:len(seg)]  = seg
            else:       arr[i,-len(seg):] = seg
        return np.nanmean(arr,0)

    for lbl,f in (("first",True),("last",False)):
        plt.figure()
        plt.plot(_avg_curve(df_mem,f), label="mem")
        plt.plot(_avg_curve(df_non,f), label="non")
        plt.title(f"Average loss – {lbl} 100 tokens"); plt.legend(); plt.show()

# ----------- 3) ROC curves for attack-level scores -------------------------- #
for col in ("edgington_score","bestpv_score","logistic_score"):
    if col not in df_test.columns: continue
    y   = df_test.membership_label.values
    s   = -df_test[col].values
    auc = roc_auc_score(y, s)
    fpr,tpr,_ = roc_curve(y,s)
    plt.figure(); plt.plot(fpr, tpr, label=f"AUC {auc:.3f}")
    plt.title(col); plt.xlabel("FPR"); plt.ylabel("TPR"); plt.legend(); plt.show()

print("Diagnostics done – folder:", RUN_DIR)

In [ ]:
###############################################################################
# Cell 8 – Detailed feature table  +  cross-dataset best-of grid              #
###############################################################################
import os, glob, json, numpy as np, pandas as pd
from sklearn.metrics import roc_auc_score, roc_curve
import matplotlib.pyplot as plt   # only if you want to eyeball results

# ─────────── 1) CONFIG – pick ONE dataset / (K,W) for the feature table ─────
MODEL_TAG  = "pythia70m-dedup"        # ← exactly as used in Cell 6
DOMAIN     = "pubmed_central"         #   one of your six datasets
SELECT_K   = 25                       #   one of the K values you swept
SELECT_W   = 18                       #   one of the W values you swept
# ─────────────────────────────────────────────────────────────────────────────

ROOT      = "10x_results_high_k_nei"
RUN_GLOB  = (f"{ROOT}/{DOMAIN}_{MODEL_TAG}/K{SELECT_K}_W{SELECT_W}/"
             f"run_*/results_{DOMAIN}_{MODEL_TAG}.csv")

# --------------------------------------------------------------------------- #
def auc_tpr(arr_mem, arr_non):
    """Return (AUC , TPR@1 %FPR) for two numeric 1-D arrays (scores: smaller→member)."""
    y = [1]*len(arr_mem) + [0]*len(arr_non)
    s = -np.concatenate([arr_mem, arr_non])
    auc  = roc_auc_score(y, s)
    fpr, tpr, _ = roc_curve(y, s)
    return auc, 100*tpr[np.argmin(np.abs(fpr-0.01))]

skip_cols = {"text_index","membership_label","set_split",
             "edgington_score","logistic_score","bestpv_score",
             "loss_seq_orig","nei_texts"}

# ==================== PART A – per-feature table (AUC & TPR together) ======= #
rows = []
for csv_path in glob.glob(RUN_GLOB):
    df        = pd.read_csv(csv_path)
    df_test   = df[df.set_split=="test"]
    mem, non  = (df_test[df_test.membership_label==lbl]
                 for lbl in (1,0))

    run_id = os.path.basename(os.path.dirname(csv_path))   # run_00 …

    for feat in (c for c in df_test.columns if c not in skip_cols):
        auc, tpr = auc_tpr(mem[feat], non[feat])
        rows.append({"feature": feat, "run": run_id,
                     "AUC": auc, "TPR01": tpr})

if not rows:
    raise RuntimeError(f"No CSV files found for {DOMAIN}  K={SELECT_K}  W={SELECT_W}")

df_feat = pd.DataFrame(rows)

# ---- average over the 10 runs & build one tidy table ----------------------- #
tbl_feat = (df_feat
            .groupby("feature")[["AUC","TPR01"]]
            .mean()
            .round({"AUC":3, "TPR01":2})
            .T)                               #   metrics as rows
tbl_feat.index.name = "metric"

print(f"\n===  PER-FEATURE metrics — {DOMAIN}   (K={SELECT_K}, W={SELECT_W}) ===")
display(tbl_feat)

# overwrite every time
out_dir  = f"{ROOT}/{DOMAIN}_{MODEL_TAG}"
tbl_feat.to_csv(f"{out_dir}/feature_metrics_K{SELECT_K}_W{SELECT_W}.csv")
print("saved per-feature table →", out_dir)

# ================= PART B – best-of-grid OVERVIEW for every dataset ========= #
metrics = ["auc_edgington","auc_fisher","auc_pearson",
           "auc_george","auc_log",
           "tpr01_edgington","tpr01_fisher","tpr01_pearson",
           "tpr01_george","tpr01_log"]

rows_best = []
for gb_path in glob.glob(f"{ROOT}/*_{MODEL_TAG}/grid_best.json"):
    domain = os.path.basename(os.path.dirname(gb_path)).rsplit("_",1)[0]
    best   = json.load(open(gb_path))

    row = {"domain": domain}
    for m in metrics:
        if m in best:
            d = best[m]
            # tuple: (value , K , W)
            if m.startswith("auc_log") or m.startswith("tpr01_log"):
                row[m] = (round(d["score"], 3 if m.startswith("auc") else 2),
                        d["K"],             # keep K
                        "γ="+str(GRID_NEI_GAMMA[GRID_NEI_WEIGHT.index(d["W"])])
                        if d["K"] else "-")
        else:
            row[m] = np.nan
    rows_best.append(row)

df_best = (pd.DataFrame(rows_best)
             .set_index("domain")
             .sort_index())

print(f"\n===  BEST-OF-GRID per domain — model {MODEL_TAG} ===")
display(df_best)

# single output file, overwritten on every run
out_csv = f"{ROOT}/overall_best_{MODEL_TAG}.csv"
df_best.to_csv(out_csv)
print("saved overall-best table →", out_csv)

===  PER-FEATURE metrics — pubmed_central   (K=25, W=18) ===

feature,apen_1000,apen_600,apen_800,cal_200,cal_200_rep1_diff,cal_200_rep2_diff,cal_300,cal_300_rep1_diff,cal_300_rep2_diff,cal_T,...,ppl_200_rep2_diff,ppl_300,ppl_300_rep1_diff,ppl_300_rep2_diff,ppl_T,ppl_T_rep1_diff,ppl_T_rep2_diff,slope_1000,slope_600,slope_800
metric,,,,,,,,,,,,,,,,,,,,,
AUC,0.60,0.599,0.584,0.826,0.829,0.831,0.812,0.818,0.819,0.819,...,0.814,0.791,0.792,0.792,0.792,0.792,0.79,0.61,0.606,0.639
TPR01,2.09,2.350,1.950,27.850,27.180,27.240,31.130,26.920,28.140,27.990,...,16.100,14.100,12.990,13.400,12.120,11.800,10.61,2.97,1.220,2.670

saved per-feature table → 10x_results_high_k_nei/pubmed_central_pythia70m-dedup

===  BEST-OF-GRID per domain — model pythia70m-dedup ===

,auc_edgington,auc_fisher,auc_pearson,auc_george,auc_log,tpr01_edgington,tpr01_fisher,tpr01_pearson,tpr01_george,tpr01_log
domain,,,,,,,,,,
arxiv,"(0.755, 0, 0)","(0.28, 25, 72)","(0.731, 0, 0)","(0.758, 0, 0)","(0.767, 0, 0)","(0.15, 0, 0)","(0.0, 100, 72)","(0.11, 0, 0)","(0.21, 0, 0)","(0.19, 0, 0)"
dm_mathematics,"(0.931, 0, 0)","(0.104, 25, 72)","(0.912, 0, 0)","(0.943, 0, 0)","(0.927, 0, 0)","(0.26, 0, 0)","(0.0, 0, 0)","(0.1, 0, 0)","(0.58, 0, 0)","(0.45, 25, 9)"
github,"(0.857, 25, 9)","(0.166, 100, 72)","(0.858, 25, 9)","(0.855, 0, 0)","(0.86, 0, 0)","(0.5, 25, 9)","(0.0, 25, 9)","(0.44, 100, 72)","(0.47, 25, 18)","(0.55, 0, 0)"
hackernews,"(0.577, 0, 0)","(0.433, 25, 72)","(0.569, 100, 9)","(0.577, 25, 9)","(0.568, 0, 0)","(0.04, 25, 18)","(0.01, 25, 72)","(0.02, 25, 36)","(0.05, 0, 0)","(0.03, 0, 0)"
pile_cc,"(0.538, 0, 0)","(0.478, 25, 72)","(0.538, 25, 18)","(0.536, 100, 9)","(0.531, 0, 0)","(0.03, 100, 72)","(0.01, 100, 72)","(0.03, 100, 18)","(0.03, 100, 18)","(0.02, 0, 0)"
pubmed_central,"(0.819, 0, 0)","(0.243, 25, 72)","(0.802, 0, 0)","(0.82, 0, 0)","(0.828, 0, 0)","(0.22, 25, 9)","(0.0, 0, 0)","(0.19, 100, 9)","(0.28, 100, 9)","(0.26, 0, 0)"

saved overall-best table → 10x_results_high_k_nei/overall_best_pythia70m-dedup.csv

In [ ]:
# ╔═══════════════════════════════════════════════════════════════════╗
# ║  Small helper to preview CAMIA CSVs as real tables                ║
# ╚═══════════════════════════════════════════════════════════════════╝
import glob, pandas as pd, os, textwrap, importlib
from pathlib import Path

def show_cam_tables(
    path_pattern: str,
    keep: list[str] | None = None,
    drop: list[str] | None = None,
    show_path_column: bool = False,
    max_rows: int = 100,
    max_columns: int = 100
):
    """
    path_pattern : a single CSV file or a glob, e.g.
                   'experiment/*_pythia70m-dedup/*/run_*/results_*.csv'
    keep         : list of column names to KEEP (None → keep all)
    drop         : list of column names to DROP (None → drop nothing)
    show_path_column : if True, adds the CSV filename as the first column
    max_rows     : truncate huge tables for readability
    """
    files = sorted(glob.glob(path_pattern))
    if not files:
        raise FileNotFoundError(f"No CSVs matched: {path_pattern}")

    dfs = []
    for csv in files:
        df = pd.read_csv(csv, low_memory=False)
        if keep is not None:
            # allow for “some files don’t have this column”
            df = df[[c for c in keep if c in df.columns]]
        if drop is not None:
            df = df.drop(columns=drop, errors="ignore")
        if show_path_column:
            df.insert(0, "csv_path", os.path.relpath(csv))
        dfs.append(df)

    big = pd.concat(dfs, ignore_index=True)
    if len(big) > max_rows:
        print(f"⚠ Truncated to first {max_rows} rows "
              f"(table has {len(big)} rows in total)")
        big = big.head(max_rows)

    # wrap very long column names so the table stays readable
    big.rename(columns=lambda c: textwrap.fill(c, 24), inplace=True)

    # pretty display if ace_tools is around, else fall back to print
    try:
        ace_tools = importlib.import_module("ace_tools")
        ace_tools.display_dataframe_to_user("camia_csv_preview", big)
    except ModuleNotFoundError:
        from IPython.display import display
        display(big)

# ───────────── EXAMPLE ─────────────
#Show *all* columns from every run of your ARXIV experiment
show_cam_tables(
     "10x_results_highloss_k_nei/pubmed_central_pythia70m-dedup/feature_metrics_K25_W18.csv",
     show_path_column=True,
 )

#Or keep just a few columns:
show_cam_tables(
     "experiment/arxiv_pythia70m-dedup/*/run_*/results_*.csv",
     keep=["membership_label", "cut_200", "cb_const1", "nei_delta"],
     show_path_column=True,
 )

,csv_path,metric,apen_1000,apen_600,apen_800,cal_200,cal_200_rep1_diff,cal_200_rep2_diff,cal_300,cal_300_rep1_diff,...,ppl_200_rep2_diff,ppl_300,ppl_300_rep1_diff,ppl_300_rep2_diff,ppl_T,ppl_T_rep1_diff,ppl_T_rep2_diff,slope_1000,slope_600,slope_800
0,10x_results_highloss_k_nei/pubmed_central_pyth...,AUC,0.40,0.401,0.416,0.826,0.829,0.831,0.812,0.818,...,0.814,0.791,0.792,0.792,0.792,0.792,0.79,0.39,0.394,0.361
1,10x_results_highloss_k_nei/pubmed_central_pyth...,TPR01,0.58,0.730,0.120,27.850,27.180,27.240,31.130,26.920,...,16.100,14.100,12.990,13.400,12.120,11.800,10.61,0.41,0.120,0.760

⚠ Truncated to first 100 rows (table has 63000 rows in total)

,csv_path,membership_label,cut_200,cb_const1,nei_delta
0,experiment/arxiv_pythia70m-dedup/K0_W0/run_00/...,1,3.873757,0.783920,NaN
1,experiment/arxiv_pythia70m-dedup/K0_W0/run_00/...,1,2.618152,0.557789,NaN
2,experiment/arxiv_pythia70m-dedup/K0_W0/run_00/...,1,3.057221,0.623116,NaN
3,experiment/arxiv_pythia70m-dedup/K0_W0/run_00/...,1,2.776782,0.618090,NaN
4,experiment/arxiv_pythia70m-dedup/K0_W0/run_00/...,1,2.720650,0.608040,NaN
...,...,...,...,...,...
95,experiment/arxiv_pythia70m-dedup/K0_W0/run_00/...,1,3.319693,0.723618,NaN
96,experiment/arxiv_pythia70m-dedup/K0_W0/run_00/...,1,3.036233,0.748744,NaN
97,experiment/arxiv_pythia70m-dedup/K0_W0/run_00/...,1,3.325033,0.628141,NaN
98,experiment/arxiv_pythia70m-dedup/K0_W0/run_00/...,1,3.806827,0.773869,NaN
99,experiment/arxiv_pythia70m-dedup/K0_W0/run_00/...,1,3.881519,0.768844,NaN

In [37]:
import json, random, textwrap

domain = "arxiv"                 # or whatever you used
split  = "ngram_7_0.2"
tag    = "member"                # or "nonmember"
row_id = 17                      # pick any 0 ≤ id < num_samples

cache_path = f"cache/neigh_{domain}_{split}_{tag}.json"
with open(cache_path) as f:
    table = json.load(f)

orig = all_members[row_id]       # already in the notebook namespace
print("ORIGINAL:\n", textwrap.fill(orig, 90), "\n")

print("NEIGHBOURS:")
for n in table[row_id][:10]:
    print(" –", textwrap.shorten(n, width=120, placeholder=" […]"))

ORIGINAL:
 --- abstract: 'We study the asymptotic behavior of oscillatory Riemann-Hilbert problems
arising in the AKNS hierarchy of integrable nonlinear PDE’s. Our method is based on the
Deift-Zhou nonlinear steepest descent method in which the given Riemann-Hilbert problem
localizes to small neighborhoods of stationary phase points. In their original work, Deift
and Zhou only considered analytic phase functions. Subsequently Varzugin extended the
Deift-Zhou method to a certain restricted class of non-analytic phase functions. In this
paper, we extend Varzugin’s method to a substantially more general class of non-analytic
phase functions. In our work real variable methods play a key role.' address: 'Yen Do,
Department of Mathematics, UCLA, Los Angeles, CA 90095-1555, USA' author: - Yen Do title:
'A nonlinear stationary phase method for oscillatory Riemann-Hilbert problems' ---
Introduction ============  In many studies of asymptotical behaviors of nonlinear systems,
the following Riemann-Hilbert problem (RHP) appears: given $J$ an invertible matrix-valued
function on $\mathbb R$, we look for a matrix-valued function $M(\lambda)$ which is
analytic on $\mathbb C \setminus \mathbb R$ and satisfies the following jump condition:
$$\begin{aligned}     M_+(\lambda) &=& M_-(\lambda)J(\lambda), \; \; \text{for a.e. }
\lambda \in \mathbb R\end{aligned}$$ $M_\pm(\lambda)$ denote the upper and lower parts of
$M$, with appropriate normalization at

NEIGHBOURS:
 – - - - abstract :'we study the asymptotic behavior of oscillatory riemann - hilbert problems arising in the akns […]
 – - - - abstract :'i study the asymptotic behavior of oscillatory riemann - hilbert problems arising in the akns […]
 – - - - abstract :'we study the asymptotic behavior of oscillatory riemann - hilbert problems arising in the akns […]
 – - - - abstract :'we study the asymptotic behavior of oscillatory riemann - hilbert problems arising in the akns […]
 – - - - abstract :'we study the asymptotic behavior of oscillatory riemann - hilbert problems arising in the akns […]
 – - - - abstract :'we study the asymptotic behavior of oscillatory riemann - hilbert problems arising in the akns […]
 – - - - abstract :'we study the asymptotic behavior of oscillatory riemann - hilbert problems arising in the akns […]
 – - - - abstract :'we study the asymptotic behavior of oscillatory riemann - hilbert problems arising in the akns […]
 – - - - abstract :'we study the asymptotic behavior of oscillatory riemann - hilbert problems arising in the akns […]
 – - - - abstract :'we study the asymptotic behavior of oscillatory riemann - hilbert problems arising in the akns […]